/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateMailboxRequest model module.
 * @module model/CreateMailboxRequest
 * @version 1.0.0
 */
class CreateMailboxRequest {
    /**
     * Constructs a new <code>CreateMailboxRequest</code>.
     * @alias module:model/CreateMailboxRequest
     */
    constructor() { 
        
        CreateMailboxRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['authsource'] = 'mailcow';
    }

    /**
     * Constructs a <code>CreateMailboxRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateMailboxRequest} obj Optional instance to populate.
     * @return {module:model/CreateMailboxRequest} The populated <code>CreateMailboxRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateMailboxRequest();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('local_part')) {
                obj['local_part'] = ApiClient.convertToType(data['local_part'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('authsource')) {
                obj['authsource'] = ApiClient.convertToType(data['authsource'], 'String');
            }
            if (data.hasOwnProperty('password2')) {
                obj['password2'] = ApiClient.convertToType(data['password2'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('quota')) {
                obj['quota'] = ApiClient.convertToType(data['quota'], 'Number');
            }
            if (data.hasOwnProperty('force_pw_update')) {
                obj['force_pw_update'] = ApiClient.convertToType(data['force_pw_update'], 'Boolean');
            }
            if (data.hasOwnProperty('tls_enforce_in')) {
                obj['tls_enforce_in'] = ApiClient.convertToType(data['tls_enforce_in'], 'Boolean');
            }
            if (data.hasOwnProperty('tls_enforce_out')) {
                obj['tls_enforce_out'] = ApiClient.convertToType(data['tls_enforce_out'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateMailboxRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateMailboxRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is a string
        if (data['local_part'] && !(typeof data['local_part'] === 'string' || data['local_part'] instanceof String)) {
            throw new Error("Expected the field `local_part` to be a primitive type in the JSON string but got " + data['local_part']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['authsource'] && !(typeof data['authsource'] === 'string' || data['authsource'] instanceof String)) {
            throw new Error("Expected the field `authsource` to be a primitive type in the JSON string but got " + data['authsource']);
        }
        // ensure the json data is a string
        if (data['password2'] && !(typeof data['password2'] === 'string' || data['password2'] instanceof String)) {
            throw new Error("Expected the field `password2` to be a primitive type in the JSON string but got " + data['password2']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}



/**
 * is mailbox active or not
 * @member {Boolean} active
 */
CreateMailboxRequest.prototype['active'] = undefined;

/**
 * domain name
 * @member {String} domain
 */
CreateMailboxRequest.prototype['domain'] = undefined;

/**
 * left part of email address
 * @member {String} local_part
 */
CreateMailboxRequest.prototype['local_part'] = undefined;

/**
 * Full name of the mailbox user
 * @member {String} name
 */
CreateMailboxRequest.prototype['name'] = undefined;

/**
 * Specifies the authentication source for the mailbox.
 * @member {module:model/CreateMailboxRequest.AuthsourceEnum} authsource
 * @default 'mailcow'
 */
CreateMailboxRequest.prototype['authsource'] = 'mailcow';

/**
 * mailbox password for confirmation
 * @member {String} password2
 */
CreateMailboxRequest.prototype['password2'] = undefined;

/**
 * mailbox password when using `mailcow` as the authentication source.
 * @member {String} password
 */
CreateMailboxRequest.prototype['password'] = undefined;

/**
 * mailbox quota
 * @member {Number} quota
 */
CreateMailboxRequest.prototype['quota'] = undefined;

/**
 * forces the user to update its password on first login
 * @member {Boolean} force_pw_update
 */
CreateMailboxRequest.prototype['force_pw_update'] = undefined;

/**
 * force inbound email tls encryption
 * @member {Boolean} tls_enforce_in
 */
CreateMailboxRequest.prototype['tls_enforce_in'] = undefined;

/**
 * force oubound tmail tls encryption
 * @member {Boolean} tls_enforce_out
 */
CreateMailboxRequest.prototype['tls_enforce_out'] = undefined;





/**
 * Allowed values for the <code>authsource</code> property.
 * @enum {String}
 * @readonly
 */
CreateMailboxRequest['AuthsourceEnum'] = {

    /**
     * value: "mailcow"
     * @const
     */
    "mailcow": "mailcow",

    /**
     * value: "ldap"
     * @const
     */
    "ldap": "ldap",

    /**
     * value: "keycloak"
     * @const
     */
    "keycloak": "keycloak",

    /**
     * value: "generic-oidc"
     * @const
     */
    "generic-oidc": "generic-oidc"
};



export default CreateMailboxRequest;

