/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateSyncJobRequest model module.
 * @module model/CreateSyncJobRequest
 * @version 1.0.0
 */
class CreateSyncJobRequest {
    /**
     * Constructs a new <code>CreateSyncJobRequest</code>.
     * @alias module:model/CreateSyncJobRequest
     */
    constructor() { 
        
        CreateSyncJobRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateSyncJobRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateSyncJobRequest} obj Optional instance to populate.
     * @return {module:model/CreateSyncJobRequest} The populated <code>CreateSyncJobRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSyncJobRequest();

            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], 'String');
            }
            if (data.hasOwnProperty('host1')) {
                obj['host1'] = ApiClient.convertToType(data['host1'], 'String');
            }
            if (data.hasOwnProperty('port1')) {
                obj['port1'] = ApiClient.convertToType(data['port1'], 'String');
            }
            if (data.hasOwnProperty('user1')) {
                obj['user1'] = ApiClient.convertToType(data['user1'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('enc1')) {
                obj['enc1'] = ApiClient.convertToType(data['enc1'], 'String');
            }
            if (data.hasOwnProperty('mins_internal')) {
                obj['mins_internal'] = ApiClient.convertToType(data['mins_internal'], 'Number');
            }
            if (data.hasOwnProperty('subfolder2')) {
                obj['subfolder2'] = ApiClient.convertToType(data['subfolder2'], 'String');
            }
            if (data.hasOwnProperty('maxage')) {
                obj['maxage'] = ApiClient.convertToType(data['maxage'], 'Number');
            }
            if (data.hasOwnProperty('maxbytespersecond')) {
                obj['maxbytespersecond'] = ApiClient.convertToType(data['maxbytespersecond'], 'Number');
            }
            if (data.hasOwnProperty('timeout1')) {
                obj['timeout1'] = ApiClient.convertToType(data['timeout1'], 'Number');
            }
            if (data.hasOwnProperty('timeout2')) {
                obj['timeout2'] = ApiClient.convertToType(data['timeout2'], 'Number');
            }
            if (data.hasOwnProperty('exclude')) {
                obj['exclude'] = ApiClient.convertToType(data['exclude'], 'String');
            }
            if (data.hasOwnProperty('custom_params')) {
                obj['custom_params'] = ApiClient.convertToType(data['custom_params'], 'String');
            }
            if (data.hasOwnProperty('delete2duplicates')) {
                obj['delete2duplicates'] = ApiClient.convertToType(data['delete2duplicates'], 'Boolean');
            }
            if (data.hasOwnProperty('delete1')) {
                obj['delete1'] = ApiClient.convertToType(data['delete1'], 'Boolean');
            }
            if (data.hasOwnProperty('delete2')) {
                obj['delete2'] = ApiClient.convertToType(data['delete2'], 'Boolean');
            }
            if (data.hasOwnProperty('automap')) {
                obj['automap'] = ApiClient.convertToType(data['automap'], 'Boolean');
            }
            if (data.hasOwnProperty('skipcrossduplicates')) {
                obj['skipcrossduplicates'] = ApiClient.convertToType(data['skipcrossduplicates'], 'Boolean');
            }
            if (data.hasOwnProperty('subscribeall')) {
                obj['subscribeall'] = ApiClient.convertToType(data['subscribeall'], 'Boolean');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateSyncJobRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateSyncJobRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['parameters'] && !(typeof data['parameters'] === 'string' || data['parameters'] instanceof String)) {
            throw new Error("Expected the field `parameters` to be a primitive type in the JSON string but got " + data['parameters']);
        }
        // ensure the json data is a string
        if (data['host1'] && !(typeof data['host1'] === 'string' || data['host1'] instanceof String)) {
            throw new Error("Expected the field `host1` to be a primitive type in the JSON string but got " + data['host1']);
        }
        // ensure the json data is a string
        if (data['port1'] && !(typeof data['port1'] === 'string' || data['port1'] instanceof String)) {
            throw new Error("Expected the field `port1` to be a primitive type in the JSON string but got " + data['port1']);
        }
        // ensure the json data is a string
        if (data['user1'] && !(typeof data['user1'] === 'string' || data['user1'] instanceof String)) {
            throw new Error("Expected the field `user1` to be a primitive type in the JSON string but got " + data['user1']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['enc1'] && !(typeof data['enc1'] === 'string' || data['enc1'] instanceof String)) {
            throw new Error("Expected the field `enc1` to be a primitive type in the JSON string but got " + data['enc1']);
        }
        // ensure the json data is a string
        if (data['subfolder2'] && !(typeof data['subfolder2'] === 'string' || data['subfolder2'] instanceof String)) {
            throw new Error("Expected the field `subfolder2` to be a primitive type in the JSON string but got " + data['subfolder2']);
        }
        // ensure the json data is a string
        if (data['exclude'] && !(typeof data['exclude'] === 'string' || data['exclude'] instanceof String)) {
            throw new Error("Expected the field `exclude` to be a primitive type in the JSON string but got " + data['exclude']);
        }
        // ensure the json data is a string
        if (data['custom_params'] && !(typeof data['custom_params'] === 'string' || data['custom_params'] instanceof String)) {
            throw new Error("Expected the field `custom_params` to be a primitive type in the JSON string but got " + data['custom_params']);
        }

        return true;
    }


}



/**
 * your local mailcow mailbox
 * @member {String} parameters
 */
CreateSyncJobRequest.prototype['parameters'] = undefined;

/**
 * the smtp server where mails should be synced from
 * @member {String} host1
 */
CreateSyncJobRequest.prototype['host1'] = undefined;

/**
 * the smtp port of the target mail server
 * @member {String} port1
 */
CreateSyncJobRequest.prototype['port1'] = undefined;

/**
 * the username of the mailbox
 * @member {String} user1
 */
CreateSyncJobRequest.prototype['user1'] = undefined;

/**
 * the password of the mailbox
 * @member {String} password
 */
CreateSyncJobRequest.prototype['password'] = undefined;

/**
 * the encryption method used to connect to the mailserver
 * @member {String} enc1
 */
CreateSyncJobRequest.prototype['enc1'] = undefined;

/**
 * the interval in which messages should be syned
 * @member {Number} mins_internal
 */
CreateSyncJobRequest.prototype['mins_internal'] = undefined;

/**
 * sync into subfolder on destination (empty = do not use subfolder)
 * @member {String} subfolder2
 */
CreateSyncJobRequest.prototype['subfolder2'] = undefined;

/**
 * only sync messages up to this age in days
 * @member {Number} maxage
 */
CreateSyncJobRequest.prototype['maxage'] = undefined;

/**
 * max speed transfer limit for the sync
 * @member {Number} maxbytespersecond
 */
CreateSyncJobRequest.prototype['maxbytespersecond'] = undefined;

/**
 * timeout for connection to remote host
 * @member {Number} timeout1
 */
CreateSyncJobRequest.prototype['timeout1'] = undefined;

/**
 * timeout for connection to local host
 * @member {Number} timeout2
 */
CreateSyncJobRequest.prototype['timeout2'] = undefined;

/**
 * exclude objects (regex)
 * @member {String} exclude
 */
CreateSyncJobRequest.prototype['exclude'] = undefined;

/**
 * custom parameters
 * @member {String} custom_params
 */
CreateSyncJobRequest.prototype['custom_params'] = undefined;

/**
 * delete duplicates on destination (--delete2duplicates)
 * @member {Boolean} delete2duplicates
 */
CreateSyncJobRequest.prototype['delete2duplicates'] = undefined;

/**
 * delete from source when completed (--delete1)
 * @member {Boolean} delete1
 */
CreateSyncJobRequest.prototype['delete1'] = undefined;

/**
 * delete messages on destination that are not on source (--delete2)
 * @member {Boolean} delete2
 */
CreateSyncJobRequest.prototype['delete2'] = undefined;

/**
 * try to automap folders (\"Sent items\", \"Sent\" => \"Sent\" etc.) (--automap)
 * @member {Boolean} automap
 */
CreateSyncJobRequest.prototype['automap'] = undefined;

/**
 * skip duplicate messages across folders (first come, first serve) (--skipcrossduplicates)
 * @member {Boolean} skipcrossduplicates
 */
CreateSyncJobRequest.prototype['skipcrossduplicates'] = undefined;

/**
 * subscribe all folders (--subscribeall)
 * @member {Boolean} subscribeall
 */
CreateSyncJobRequest.prototype['subscribeall'] = undefined;

/**
 * enables or disables the sync job
 * @member {Boolean} active
 */
CreateSyncJobRequest.prototype['active'] = undefined;






export default CreateSyncJobRequest;

