/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EditMailboxRatelimitsRequestAttr model module.
 * @module model/EditMailboxRatelimitsRequestAttr
 * @version 1.0.0
 */
class EditMailboxRatelimitsRequestAttr {
    /**
     * Constructs a new <code>EditMailboxRatelimitsRequestAttr</code>.
     * @alias module:model/EditMailboxRatelimitsRequestAttr
     */
    constructor() { 
        
        EditMailboxRatelimitsRequestAttr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EditMailboxRatelimitsRequestAttr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditMailboxRatelimitsRequestAttr} obj Optional instance to populate.
     * @return {module:model/EditMailboxRatelimitsRequestAttr} The populated <code>EditMailboxRatelimitsRequestAttr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditMailboxRatelimitsRequestAttr();

            if (data.hasOwnProperty('rl_frame')) {
                obj['rl_frame'] = ApiClient.convertToType(data['rl_frame'], 'String');
            }
            if (data.hasOwnProperty('rl_value')) {
                obj['rl_value'] = ApiClient.convertToType(data['rl_value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditMailboxRatelimitsRequestAttr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditMailboxRatelimitsRequestAttr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['rl_frame'] && !(typeof data['rl_frame'] === 'string' || data['rl_frame'] instanceof String)) {
            throw new Error("Expected the field `rl_frame` to be a primitive type in the JSON string but got " + data['rl_frame']);
        }

        return true;
    }


}



/**
 * contains the frame for the ratelimit h,s,m
 * @member {String} rl_frame
 */
EditMailboxRatelimitsRequestAttr.prototype['rl_frame'] = undefined;

/**
 * contains the rate for the ratelimit 10,20,50,1
 * @member {Number} rl_value
 */
EditMailboxRatelimitsRequestAttr.prototype['rl_value'] = undefined;






export default EditMailboxRatelimitsRequestAttr;

