/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EditDomainAdminUserRequestAttr model module.
 * @module model/EditDomainAdminUserRequestAttr
 * @version 1.0.0
 */
class EditDomainAdminUserRequestAttr {
    /**
     * Constructs a new <code>EditDomainAdminUserRequestAttr</code>.
     * @alias module:model/EditDomainAdminUserRequestAttr
     */
    constructor() { 
        
        EditDomainAdminUserRequestAttr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EditDomainAdminUserRequestAttr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditDomainAdminUserRequestAttr} obj Optional instance to populate.
     * @return {module:model/EditDomainAdminUserRequestAttr} The populated <code>EditDomainAdminUserRequestAttr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditDomainAdminUserRequestAttr();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('username_new')) {
                obj['username_new'] = ApiClient.convertToType(data['username_new'], 'String');
            }
            if (data.hasOwnProperty('domains')) {
                obj['domains'] = ApiClient.convertToType(data['domains'], ['String']);
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('password2')) {
                obj['password2'] = ApiClient.convertToType(data['password2'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditDomainAdminUserRequestAttr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditDomainAdminUserRequestAttr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['username_new'] && !(typeof data['username_new'] === 'string' || data['username_new'] instanceof String)) {
            throw new Error("Expected the field `username_new` to be a primitive type in the JSON string but got " + data['username_new']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['domains'])) {
            throw new Error("Expected the field `domains` to be an array in the JSON data but got " + data['domains']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['password2'] && !(typeof data['password2'] === 'string' || data['password2'] instanceof String)) {
            throw new Error("Expected the field `password2` to be a primitive type in the JSON string but got " + data['password2']);
        }

        return true;
    }


}



/**
 * is the domain admin active or not
 * @member {Boolean} active
 */
EditDomainAdminUserRequestAttr.prototype['active'] = undefined;

/**
 * the username of the domain admin, change this to change the username
 * @member {String} username_new
 */
EditDomainAdminUserRequestAttr.prototype['username_new'] = undefined;

/**
 * a list of all domains managed by this domain admin
 * @member {Array.<String>} domains
 */
EditDomainAdminUserRequestAttr.prototype['domains'] = undefined;

/**
 * the new domain admin user password
 * @member {String} password
 */
EditDomainAdminUserRequestAttr.prototype['password'] = undefined;

/**
 * the new domain admin user password for confirmation
 * @member {String} password2
 */
EditDomainAdminUserRequestAttr.prototype['password2'] = undefined;






export default EditDomainAdminUserRequestAttr;

