/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EditExternalIdentityProviderSettingsRequestAttr model module.
 * @module model/EditExternalIdentityProviderSettingsRequestAttr
 * @version 1.0.0
 */
class EditExternalIdentityProviderSettingsRequestAttr {
    /**
     * Constructs a new <code>EditExternalIdentityProviderSettingsRequestAttr</code>.
     * @alias module:model/EditExternalIdentityProviderSettingsRequestAttr
     */
    constructor() { 
        
        EditExternalIdentityProviderSettingsRequestAttr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['ignore_ssl_error'] = false;
        obj['mailpassword_flow'] = false;
        obj['periodic_sync'] = false;
        obj['import_users'] = false;
        obj['sync_interval'] = 15;
        obj['use_ssl'] = false;
        obj['use_tls'] = false;
        obj['username_field'] = 'mail';
        obj['client_scopes'] = 'openid profile email mailcow_template';
    }

    /**
     * Constructs a <code>EditExternalIdentityProviderSettingsRequestAttr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditExternalIdentityProviderSettingsRequestAttr} obj Optional instance to populate.
     * @return {module:model/EditExternalIdentityProviderSettingsRequestAttr} The populated <code>EditExternalIdentityProviderSettingsRequestAttr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditExternalIdentityProviderSettingsRequestAttr();

            if (data.hasOwnProperty('authsource')) {
                obj['authsource'] = ApiClient.convertToType(data['authsource'], 'String');
            }
            if (data.hasOwnProperty('server_url')) {
                obj['server_url'] = ApiClient.convertToType(data['server_url'], 'String');
            }
            if (data.hasOwnProperty('realm')) {
                obj['realm'] = ApiClient.convertToType(data['realm'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
            if (data.hasOwnProperty('redirect_url')) {
                obj['redirect_url'] = ApiClient.convertToType(data['redirect_url'], 'String');
            }
            if (data.hasOwnProperty('redirect_url_extra')) {
                obj['redirect_url_extra'] = ApiClient.convertToType(data['redirect_url_extra'], [Object]);
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('default_template')) {
                obj['default_template'] = ApiClient.convertToType(data['default_template'], 'String');
            }
            if (data.hasOwnProperty('mappers')) {
                obj['mappers'] = ApiClient.convertToType(data['mappers'], [Object]);
            }
            if (data.hasOwnProperty('templates')) {
                obj['templates'] = ApiClient.convertToType(data['templates'], [Object]);
            }
            if (data.hasOwnProperty('ignore_ssl_error')) {
                obj['ignore_ssl_error'] = ApiClient.convertToType(data['ignore_ssl_error'], 'Boolean');
            }
            if (data.hasOwnProperty('mailpassword_flow')) {
                obj['mailpassword_flow'] = ApiClient.convertToType(data['mailpassword_flow'], 'Boolean');
            }
            if (data.hasOwnProperty('periodic_sync')) {
                obj['periodic_sync'] = ApiClient.convertToType(data['periodic_sync'], 'Boolean');
            }
            if (data.hasOwnProperty('import_users')) {
                obj['import_users'] = ApiClient.convertToType(data['import_users'], 'Boolean');
            }
            if (data.hasOwnProperty('sync_interval')) {
                obj['sync_interval'] = ApiClient.convertToType(data['sync_interval'], 'Number');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'String');
            }
            if (data.hasOwnProperty('use_ssl')) {
                obj['use_ssl'] = ApiClient.convertToType(data['use_ssl'], 'Boolean');
            }
            if (data.hasOwnProperty('use_tls')) {
                obj['use_tls'] = ApiClient.convertToType(data['use_tls'], 'Boolean');
            }
            if (data.hasOwnProperty('basedn')) {
                obj['basedn'] = ApiClient.convertToType(data['basedn'], 'String');
            }
            if (data.hasOwnProperty('username_field')) {
                obj['username_field'] = ApiClient.convertToType(data['username_field'], 'String');
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], 'String');
            }
            if (data.hasOwnProperty('attribute_field')) {
                obj['attribute_field'] = ApiClient.convertToType(data['attribute_field'], 'String');
            }
            if (data.hasOwnProperty('binddn')) {
                obj['binddn'] = ApiClient.convertToType(data['binddn'], 'String');
            }
            if (data.hasOwnProperty('bindpass')) {
                obj['bindpass'] = ApiClient.convertToType(data['bindpass'], 'String');
            }
            if (data.hasOwnProperty('authorize_url')) {
                obj['authorize_url'] = ApiClient.convertToType(data['authorize_url'], 'String');
            }
            if (data.hasOwnProperty('token_url')) {
                obj['token_url'] = ApiClient.convertToType(data['token_url'], 'String');
            }
            if (data.hasOwnProperty('userinfo_url')) {
                obj['userinfo_url'] = ApiClient.convertToType(data['userinfo_url'], 'String');
            }
            if (data.hasOwnProperty('client_scopes')) {
                obj['client_scopes'] = ApiClient.convertToType(data['client_scopes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditExternalIdentityProviderSettingsRequestAttr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditExternalIdentityProviderSettingsRequestAttr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['authsource'] && !(typeof data['authsource'] === 'string' || data['authsource'] instanceof String)) {
            throw new Error("Expected the field `authsource` to be a primitive type in the JSON string but got " + data['authsource']);
        }
        // ensure the json data is a string
        if (data['server_url'] && !(typeof data['server_url'] === 'string' || data['server_url'] instanceof String)) {
            throw new Error("Expected the field `server_url` to be a primitive type in the JSON string but got " + data['server_url']);
        }
        // ensure the json data is a string
        if (data['realm'] && !(typeof data['realm'] === 'string' || data['realm'] instanceof String)) {
            throw new Error("Expected the field `realm` to be a primitive type in the JSON string but got " + data['realm']);
        }
        // ensure the json data is a string
        if (data['client_id'] && !(typeof data['client_id'] === 'string' || data['client_id'] instanceof String)) {
            throw new Error("Expected the field `client_id` to be a primitive type in the JSON string but got " + data['client_id']);
        }
        // ensure the json data is a string
        if (data['client_secret'] && !(typeof data['client_secret'] === 'string' || data['client_secret'] instanceof String)) {
            throw new Error("Expected the field `client_secret` to be a primitive type in the JSON string but got " + data['client_secret']);
        }
        // ensure the json data is a string
        if (data['redirect_url'] && !(typeof data['redirect_url'] === 'string' || data['redirect_url'] instanceof String)) {
            throw new Error("Expected the field `redirect_url` to be a primitive type in the JSON string but got " + data['redirect_url']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['redirect_url_extra'])) {
            throw new Error("Expected the field `redirect_url_extra` to be an array in the JSON data but got " + data['redirect_url_extra']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }
        // ensure the json data is a string
        if (data['default_template'] && !(typeof data['default_template'] === 'string' || data['default_template'] instanceof String)) {
            throw new Error("Expected the field `default_template` to be a primitive type in the JSON string but got " + data['default_template']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['mappers'])) {
            throw new Error("Expected the field `mappers` to be an array in the JSON data but got " + data['mappers']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['templates'])) {
            throw new Error("Expected the field `templates` to be an array in the JSON data but got " + data['templates']);
        }
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }
        // ensure the json data is a string
        if (data['port'] && !(typeof data['port'] === 'string' || data['port'] instanceof String)) {
            throw new Error("Expected the field `port` to be a primitive type in the JSON string but got " + data['port']);
        }
        // ensure the json data is a string
        if (data['basedn'] && !(typeof data['basedn'] === 'string' || data['basedn'] instanceof String)) {
            throw new Error("Expected the field `basedn` to be a primitive type in the JSON string but got " + data['basedn']);
        }
        // ensure the json data is a string
        if (data['username_field'] && !(typeof data['username_field'] === 'string' || data['username_field'] instanceof String)) {
            throw new Error("Expected the field `username_field` to be a primitive type in the JSON string but got " + data['username_field']);
        }
        // ensure the json data is a string
        if (data['filter'] && !(typeof data['filter'] === 'string' || data['filter'] instanceof String)) {
            throw new Error("Expected the field `filter` to be a primitive type in the JSON string but got " + data['filter']);
        }
        // ensure the json data is a string
        if (data['attribute_field'] && !(typeof data['attribute_field'] === 'string' || data['attribute_field'] instanceof String)) {
            throw new Error("Expected the field `attribute_field` to be a primitive type in the JSON string but got " + data['attribute_field']);
        }
        // ensure the json data is a string
        if (data['binddn'] && !(typeof data['binddn'] === 'string' || data['binddn'] instanceof String)) {
            throw new Error("Expected the field `binddn` to be a primitive type in the JSON string but got " + data['binddn']);
        }
        // ensure the json data is a string
        if (data['bindpass'] && !(typeof data['bindpass'] === 'string' || data['bindpass'] instanceof String)) {
            throw new Error("Expected the field `bindpass` to be a primitive type in the JSON string but got " + data['bindpass']);
        }
        // ensure the json data is a string
        if (data['authorize_url'] && !(typeof data['authorize_url'] === 'string' || data['authorize_url'] instanceof String)) {
            throw new Error("Expected the field `authorize_url` to be a primitive type in the JSON string but got " + data['authorize_url']);
        }
        // ensure the json data is a string
        if (data['token_url'] && !(typeof data['token_url'] === 'string' || data['token_url'] instanceof String)) {
            throw new Error("Expected the field `token_url` to be a primitive type in the JSON string but got " + data['token_url']);
        }
        // ensure the json data is a string
        if (data['userinfo_url'] && !(typeof data['userinfo_url'] === 'string' || data['userinfo_url'] instanceof String)) {
            throw new Error("Expected the field `userinfo_url` to be a primitive type in the JSON string but got " + data['userinfo_url']);
        }
        // ensure the json data is a string
        if (data['client_scopes'] && !(typeof data['client_scopes'] === 'string' || data['client_scopes'] instanceof String)) {
            throw new Error("Expected the field `client_scopes` to be a primitive type in the JSON string but got " + data['client_scopes']);
        }

        return true;
    }


}



/**
 * Specifies the type of the Identity Provider
 * @member {module:model/EditExternalIdentityProviderSettingsRequestAttr.AuthsourceEnum} authsource
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['authsource'] = undefined;

/**
 * The base URL of your Keycloak server. Required if `authsource` is keycloak.
 * @member {String} server_url
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['server_url'] = undefined;

/**
 * The Keycloak realm where the mailcow client is configured. Required if `authsource` is keycloak.
 * @member {String} realm
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['realm'] = undefined;

/**
 * The Client ID assigned to mailcow Client in OIDC Provider. Required if `authsource` is keycloak or generic-oidc.
 * @member {String} client_id
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['client_id'] = undefined;

/**
 * The Client Secret assigned to mailcow Client in OIDC Provider. Required if `authsource` is keycloak or generic-oidc.
 * @member {String} client_secret
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['client_secret'] = undefined;

/**
 * The redirect URL that OIDC Provider will use after authentication. Required if `authsource` is keycloak or generic-oidc.
 * @member {String} redirect_url
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['redirect_url'] = undefined;

/**
 * Additional redirect URLs that OIDC Provider can use after authentication if valid.
 * @member {Array.<Object>} redirect_url_extra
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['redirect_url_extra'] = undefined;

/**
 * Specifies the Keycloak version. Required if `authsource` is keycloak.
 * @member {String} version
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['version'] = undefined;

/**
 * (Optional) If no matching Attribute Mapping exists for a User, the default template will be used for creating the mailbox, but not for updating the mailbox.
 * @member {String} default_template
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['default_template'] = undefined;

/**
 * (Optional) Attribute values used to match a mailbox template. Each element corresponds to the respective index in the templates array (i.e., the first element matches the first element of templates, the second matches the second, and so on).
 * @member {Array.<Object>} mappers
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['mappers'] = undefined;

/**
 * (Optional) Defines the mailbox templates to be assigned. Each element corresponds to the respective index in the `mappers` array.
 * @member {Array.<Object>} templates
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['templates'] = undefined;

/**
 * If enabled, SSL certificate validation is bypassed
 * @member {Boolean} ignore_ssl_error
 * @default false
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['ignore_ssl_error'] = false;

/**
 * If enabled, mailcow will attempt to validate user credentials using the Keycloak Admin REST API instead of relying solely on the Authorization Code Flow.
 * @member {Boolean} mailpassword_flow
 * @default false
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['mailpassword_flow'] = false;

/**
 * If enabled, mailcow periodically performs a full sync of all users from Keycloak or LDAP.
 * @member {Boolean} periodic_sync
 * @default false
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['periodic_sync'] = false;

/**
 * If enabled, new users are automatically imported from Keycloak or LDAP into mailcow.
 * @member {Boolean} import_users
 * @default false
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['import_users'] = false;

/**
 * Defines the time interval (in minutes) for periodic synchronization and user imports.
 * @member {Number} sync_interval
 * @default 15
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['sync_interval'] = 15;

/**
 * The address of your LDAP server. You can provide a single hostname or a comma-separated list of hosts for fallback in case the primary server is unreachable. Required if `authsource` is ldap.
 * @member {String} host
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['host'] = undefined;

/**
 * The port used to connect to the LDAP server. Required if `authsource` is ldap.
 * @member {String} port
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['port'] = undefined;

/**
 * enable LDAPS connection. If Port is set to 389 it will be overriden to 636.
 * @member {Boolean} use_ssl
 * @default false
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['use_ssl'] = false;

/**
 * enable TLS connection. TLS is recommended over SSL. SSL Ports cannot be used.
 * @member {Boolean} use_tls
 * @default false
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['use_tls'] = false;

/**
 * The Distinguished Name (DN) from which searches will be performed. Required if `authsource` is ldap.
 * @member {String} basedn
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['basedn'] = undefined;

/**
 * The LDAP attribute used to identify users during authentication. Required if `authsource` is ldap.
 * @member {String} username_field
 * @default 'mail'
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['username_field'] = 'mail';

/**
 * An optional LDAP search filter to refine which users can authenticate.
 * @member {String} filter
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['filter'] = undefined;

/**
 * Specifies an LDAP attribute that holds a specific value which can be mapped to a mailbox template using the Attribute Mapping section. Required if `authsource` is ldap.
 * @member {String} attribute_field
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['attribute_field'] = undefined;

/**
 * The Distinguished Name (DN) of the LDAP user that will be used to authenticate and perform LDAP searches. This account should have sufficient permissions to read the required attributes. Required if `authsource` is ldap.
 * @member {String} binddn
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['binddn'] = undefined;

/**
 * The password for the Bind DN user. It is required for authentication when connecting to the LDAP server. Required if `authsource` is ldap.
 * @member {String} bindpass
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['bindpass'] = undefined;

/**
 * The OIDC provider's authorization server URL. Required if `authsource` is generic-oidc.
 * @member {String} authorize_url
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['authorize_url'] = undefined;

/**
 * The OIDC provider's token server URL. Required if `authsource` is generic-oidc.
 * @member {String} token_url
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['token_url'] = undefined;

/**
 * The OIDC provider's user info server URL. Required if `authsource` is generic-oidc.
 * @member {String} userinfo_url
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['userinfo_url'] = undefined;

/**
 * Specifies the OIDC scopes requested during authentication.
 * @member {String} client_scopes
 * @default 'openid profile email mailcow_template'
 */
EditExternalIdentityProviderSettingsRequestAttr.prototype['client_scopes'] = 'openid profile email mailcow_template';





/**
 * Allowed values for the <code>authsource</code> property.
 * @enum {String}
 * @readonly
 */
EditExternalIdentityProviderSettingsRequestAttr['AuthsourceEnum'] = {

    /**
     * value: "ldap"
     * @const
     */
    "ldap": "ldap",

    /**
     * value: "keycloak"
     * @const
     */
    "keycloak": "keycloak",

    /**
     * value: "generic-oidc"
     * @const
     */
    "generic-oidc": "generic-oidc"
};



export default EditExternalIdentityProviderSettingsRequestAttr;

