/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenerateDKIMKeyRequest model module.
 * @module model/GenerateDKIMKeyRequest
 * @version 1.0.0
 */
class GenerateDKIMKeyRequest {
    /**
     * Constructs a new <code>GenerateDKIMKeyRequest</code>.
     * @alias module:model/GenerateDKIMKeyRequest
     */
    constructor() { 
        
        GenerateDKIMKeyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenerateDKIMKeyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateDKIMKeyRequest} obj Optional instance to populate.
     * @return {module:model/GenerateDKIMKeyRequest} The populated <code>GenerateDKIMKeyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateDKIMKeyRequest();

            if (data.hasOwnProperty('dkim_selector')) {
                obj['dkim_selector'] = ApiClient.convertToType(data['dkim_selector'], 'String');
            }
            if (data.hasOwnProperty('domains')) {
                obj['domains'] = ApiClient.convertToType(data['domains'], 'String');
            }
            if (data.hasOwnProperty('key_size')) {
                obj['key_size'] = ApiClient.convertToType(data['key_size'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GenerateDKIMKeyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GenerateDKIMKeyRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['dkim_selector'] && !(typeof data['dkim_selector'] === 'string' || data['dkim_selector'] instanceof String)) {
            throw new Error("Expected the field `dkim_selector` to be a primitive type in the JSON string but got " + data['dkim_selector']);
        }
        // ensure the json data is a string
        if (data['domains'] && !(typeof data['domains'] === 'string' || data['domains'] instanceof String)) {
            throw new Error("Expected the field `domains` to be a primitive type in the JSON string but got " + data['domains']);
        }

        return true;
    }


}



/**
 * the DKIM selector default dkim
 * @member {String} dkim_selector
 */
GenerateDKIMKeyRequest.prototype['dkim_selector'] = undefined;

/**
 * a list of domains for which a dkim key should be generated
 * @member {String} domains
 */
GenerateDKIMKeyRequest.prototype['domains'] = undefined;

/**
 * the key size (1024, 2048, 3072 or 4096)
 * @member {Number} key_size
 */
GenerateDKIMKeyRequest.prototype['key_size'] = undefined;






export default GenerateDKIMKeyRequest;

