/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateMailboxRequestAttr model module.
 * @module model/UpdateMailboxRequestAttr
 * @version 1.0.0
 */
class UpdateMailboxRequestAttr {
    /**
     * Constructs a new <code>UpdateMailboxRequestAttr</code>.
     * @alias module:model/UpdateMailboxRequestAttr
     */
    constructor() { 
        
        UpdateMailboxRequestAttr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateMailboxRequestAttr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateMailboxRequestAttr} obj Optional instance to populate.
     * @return {module:model/UpdateMailboxRequestAttr} The populated <code>UpdateMailboxRequestAttr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateMailboxRequestAttr();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('force_pw_update')) {
                obj['force_pw_update'] = ApiClient.convertToType(data['force_pw_update'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('authsource')) {
                obj['authsource'] = ApiClient.convertToType(data['authsource'], 'String');
            }
            if (data.hasOwnProperty('password2')) {
                obj['password2'] = ApiClient.convertToType(data['password2'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('quota')) {
                obj['quota'] = ApiClient.convertToType(data['quota'], 'Number');
            }
            if (data.hasOwnProperty('sender_acl')) {
                obj['sender_acl'] = ApiClient.convertToType(data['sender_acl'], Object);
            }
            if (data.hasOwnProperty('sogo_access')) {
                obj['sogo_access'] = ApiClient.convertToType(data['sogo_access'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateMailboxRequestAttr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateMailboxRequestAttr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['authsource'] && !(typeof data['authsource'] === 'string' || data['authsource'] instanceof String)) {
            throw new Error("Expected the field `authsource` to be a primitive type in the JSON string but got " + data['authsource']);
        }
        // ensure the json data is a string
        if (data['password2'] && !(typeof data['password2'] === 'string' || data['password2'] instanceof String)) {
            throw new Error("Expected the field `password2` to be a primitive type in the JSON string but got " + data['password2']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}



/**
 * is mailbox active or not
 * @member {Boolean} active
 */
UpdateMailboxRequestAttr.prototype['active'] = undefined;

/**
 * force user to change password on next login
 * @member {Boolean} force_pw_update
 */
UpdateMailboxRequestAttr.prototype['force_pw_update'] = undefined;

/**
 * Full name of the mailbox user
 * @member {String} name
 */
UpdateMailboxRequestAttr.prototype['name'] = undefined;

/**
 * Specifies the authentication source for the mailbox.
 * @member {module:model/UpdateMailboxRequestAttr.AuthsourceEnum} authsource
 */
UpdateMailboxRequestAttr.prototype['authsource'] = undefined;

/**
 * new mailbox password for confirmation
 * @member {String} password2
 */
UpdateMailboxRequestAttr.prototype['password2'] = undefined;

/**
 * new mailbox password when using `mailcow` as the authentication source.
 * @member {String} password
 */
UpdateMailboxRequestAttr.prototype['password'] = undefined;

/**
 * mailbox quota
 * @member {Number} quota
 */
UpdateMailboxRequestAttr.prototype['quota'] = undefined;

/**
 * list of allowed send from addresses
 * @member {Object} sender_acl
 */
UpdateMailboxRequestAttr.prototype['sender_acl'] = undefined;

/**
 * is access to SOGo webmail active or not
 * @member {Boolean} sogo_access
 */
UpdateMailboxRequestAttr.prototype['sogo_access'] = undefined;





/**
 * Allowed values for the <code>authsource</code> property.
 * @enum {String}
 * @readonly
 */
UpdateMailboxRequestAttr['AuthsourceEnum'] = {

    /**
     * value: "mailcow"
     * @const
     */
    "mailcow": "mailcow",

    /**
     * value: "ldap"
     * @const
     */
    "ldap": "ldap",

    /**
     * value: "keycloak"
     * @const
     */
    "keycloak": "keycloak",

    /**
     * value: "generic-oidc"
     * @const
     */
    "generic-oidc": "generic-oidc"
};



export default UpdateMailboxRequestAttr;

