/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateSyncJobRequestAttr model module.
 * @module model/UpdateSyncJobRequestAttr
 * @version 1.0.0
 */
class UpdateSyncJobRequestAttr {
    /**
     * Constructs a new <code>UpdateSyncJobRequestAttr</code>.
     * @alias module:model/UpdateSyncJobRequestAttr
     */
    constructor() { 
        
        UpdateSyncJobRequestAttr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateSyncJobRequestAttr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateSyncJobRequestAttr} obj Optional instance to populate.
     * @return {module:model/UpdateSyncJobRequestAttr} The populated <code>UpdateSyncJobRequestAttr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSyncJobRequestAttr();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('automap')) {
                obj['automap'] = ApiClient.convertToType(data['automap'], 'Boolean');
            }
            if (data.hasOwnProperty('custom_params')) {
                obj['custom_params'] = ApiClient.convertToType(data['custom_params'], 'String');
            }
            if (data.hasOwnProperty('delete1')) {
                obj['delete1'] = ApiClient.convertToType(data['delete1'], 'Boolean');
            }
            if (data.hasOwnProperty('delete2')) {
                obj['delete2'] = ApiClient.convertToType(data['delete2'], 'Boolean');
            }
            if (data.hasOwnProperty('delete2duplicates')) {
                obj['delete2duplicates'] = ApiClient.convertToType(data['delete2duplicates'], 'Boolean');
            }
            if (data.hasOwnProperty('enc1')) {
                obj['enc1'] = ApiClient.convertToType(data['enc1'], 'String');
            }
            if (data.hasOwnProperty('exclude')) {
                obj['exclude'] = ApiClient.convertToType(data['exclude'], 'String');
            }
            if (data.hasOwnProperty('host1')) {
                obj['host1'] = ApiClient.convertToType(data['host1'], 'String');
            }
            if (data.hasOwnProperty('maxage')) {
                obj['maxage'] = ApiClient.convertToType(data['maxage'], 'Number');
            }
            if (data.hasOwnProperty('maxbytespersecond')) {
                obj['maxbytespersecond'] = ApiClient.convertToType(data['maxbytespersecond'], 'Number');
            }
            if (data.hasOwnProperty('mins_interval')) {
                obj['mins_interval'] = ApiClient.convertToType(data['mins_interval'], 'Number');
            }
            if (data.hasOwnProperty('password1')) {
                obj['password1'] = ApiClient.convertToType(data['password1'], 'String');
            }
            if (data.hasOwnProperty('port1')) {
                obj['port1'] = ApiClient.convertToType(data['port1'], 'String');
            }
            if (data.hasOwnProperty('skipcrossduplicates')) {
                obj['skipcrossduplicates'] = ApiClient.convertToType(data['skipcrossduplicates'], 'Boolean');
            }
            if (data.hasOwnProperty('subfolder2')) {
                obj['subfolder2'] = ApiClient.convertToType(data['subfolder2'], 'String');
            }
            if (data.hasOwnProperty('subscribeall')) {
                obj['subscribeall'] = ApiClient.convertToType(data['subscribeall'], 'Boolean');
            }
            if (data.hasOwnProperty('timeout1')) {
                obj['timeout1'] = ApiClient.convertToType(data['timeout1'], 'Number');
            }
            if (data.hasOwnProperty('timeout2')) {
                obj['timeout2'] = ApiClient.convertToType(data['timeout2'], 'Number');
            }
            if (data.hasOwnProperty('user1')) {
                obj['user1'] = ApiClient.convertToType(data['user1'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateSyncJobRequestAttr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateSyncJobRequestAttr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['custom_params'] && !(typeof data['custom_params'] === 'string' || data['custom_params'] instanceof String)) {
            throw new Error("Expected the field `custom_params` to be a primitive type in the JSON string but got " + data['custom_params']);
        }
        // ensure the json data is a string
        if (data['enc1'] && !(typeof data['enc1'] === 'string' || data['enc1'] instanceof String)) {
            throw new Error("Expected the field `enc1` to be a primitive type in the JSON string but got " + data['enc1']);
        }
        // ensure the json data is a string
        if (data['exclude'] && !(typeof data['exclude'] === 'string' || data['exclude'] instanceof String)) {
            throw new Error("Expected the field `exclude` to be a primitive type in the JSON string but got " + data['exclude']);
        }
        // ensure the json data is a string
        if (data['host1'] && !(typeof data['host1'] === 'string' || data['host1'] instanceof String)) {
            throw new Error("Expected the field `host1` to be a primitive type in the JSON string but got " + data['host1']);
        }
        // ensure the json data is a string
        if (data['password1'] && !(typeof data['password1'] === 'string' || data['password1'] instanceof String)) {
            throw new Error("Expected the field `password1` to be a primitive type in the JSON string but got " + data['password1']);
        }
        // ensure the json data is a string
        if (data['port1'] && !(typeof data['port1'] === 'string' || data['port1'] instanceof String)) {
            throw new Error("Expected the field `port1` to be a primitive type in the JSON string but got " + data['port1']);
        }
        // ensure the json data is a string
        if (data['subfolder2'] && !(typeof data['subfolder2'] === 'string' || data['subfolder2'] instanceof String)) {
            throw new Error("Expected the field `subfolder2` to be a primitive type in the JSON string but got " + data['subfolder2']);
        }
        // ensure the json data is a string
        if (data['user1'] && !(typeof data['user1'] === 'string' || data['user1'] instanceof String)) {
            throw new Error("Expected the field `user1` to be a primitive type in the JSON string but got " + data['user1']);
        }

        return true;
    }


}



/**
 * Is sync job active
 * @member {Boolean} active
 */
UpdateSyncJobRequestAttr.prototype['active'] = undefined;

/**
 * Try to automap folders (\"Sent items\", \"Sent\" => \"Sent\" etc.)
 * @member {Boolean} automap
 */
UpdateSyncJobRequestAttr.prototype['automap'] = undefined;

/**
 * Custom parameters passed to imapsync command
 * @member {String} custom_params
 */
UpdateSyncJobRequestAttr.prototype['custom_params'] = undefined;

/**
 * Delete from source when completed
 * @member {Boolean} delete1
 */
UpdateSyncJobRequestAttr.prototype['delete1'] = undefined;

/**
 * Delete messages on destination that are not on source
 * @member {Boolean} delete2
 */
UpdateSyncJobRequestAttr.prototype['delete2'] = undefined;

/**
 * Delete duplicates on destination
 * @member {Boolean} delete2duplicates
 */
UpdateSyncJobRequestAttr.prototype['delete2duplicates'] = undefined;

/**
 * Encryption
 * @member {module:model/UpdateSyncJobRequestAttr.Enc1Enum} enc1
 */
UpdateSyncJobRequestAttr.prototype['enc1'] = undefined;

/**
 * Exclude objects (regex)
 * @member {String} exclude
 */
UpdateSyncJobRequestAttr.prototype['exclude'] = undefined;

/**
 * Hostname
 * @member {String} host1
 */
UpdateSyncJobRequestAttr.prototype['host1'] = undefined;

/**
 * Maximum age of messages in days that will be polled from remote (0 = ignore age)
 * @member {Number} maxage
 */
UpdateSyncJobRequestAttr.prototype['maxage'] = undefined;

/**
 * Max. bytes per second (0 = unlimited)
 * @member {Number} maxbytespersecond
 */
UpdateSyncJobRequestAttr.prototype['maxbytespersecond'] = undefined;

/**
 * Interval (min)
 * @member {Number} mins_interval
 */
UpdateSyncJobRequestAttr.prototype['mins_interval'] = undefined;

/**
 * Password
 * @member {String} password1
 */
UpdateSyncJobRequestAttr.prototype['password1'] = undefined;

/**
 * Port
 * @member {String} port1
 */
UpdateSyncJobRequestAttr.prototype['port1'] = undefined;

/**
 * Skip duplicate messages across folders (first come, first serve)
 * @member {Boolean} skipcrossduplicates
 */
UpdateSyncJobRequestAttr.prototype['skipcrossduplicates'] = undefined;

/**
 * Sync into subfolder on destination (empty = do not use subfolder)
 * @member {String} subfolder2
 */
UpdateSyncJobRequestAttr.prototype['subfolder2'] = undefined;

/**
 * Subscribe all folders
 * @member {Boolean} subscribeall
 */
UpdateSyncJobRequestAttr.prototype['subscribeall'] = undefined;

/**
 * Timeout for connection to remote host
 * @member {Number} timeout1
 */
UpdateSyncJobRequestAttr.prototype['timeout1'] = undefined;

/**
 * Timeout for connection to local host
 * @member {Number} timeout2
 */
UpdateSyncJobRequestAttr.prototype['timeout2'] = undefined;

/**
 * Username
 * @member {String} user1
 */
UpdateSyncJobRequestAttr.prototype['user1'] = undefined;





/**
 * Allowed values for the <code>enc1</code> property.
 * @enum {String}
 * @readonly
 */
UpdateSyncJobRequestAttr['Enc1Enum'] = {

    /**
     * value: "TLS"
     * @const
     */
    "TLS": "TLS",

    /**
     * value: "SSL"
     * @const
     */
    "SSL": "SSL",

    /**
     * value: "PLAIN"
     * @const
     */
    "PLAIN": "PLAIN"
};



export default UpdateSyncJobRequestAttr;

