/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateDomainWideFooterRequestAttr from './UpdateDomainWideFooterRequestAttr';

/**
 * The UpdateDomainWideFooterRequest model module.
 * @module model/UpdateDomainWideFooterRequest
 * @version 1.0.0
 */
class UpdateDomainWideFooterRequest {
    /**
     * Constructs a new <code>UpdateDomainWideFooterRequest</code>.
     * @alias module:model/UpdateDomainWideFooterRequest
     */
    constructor() { 
        
        UpdateDomainWideFooterRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateDomainWideFooterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDomainWideFooterRequest} obj Optional instance to populate.
     * @return {module:model/UpdateDomainWideFooterRequest} The populated <code>UpdateDomainWideFooterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDomainWideFooterRequest();

            if (data.hasOwnProperty('attr')) {
                obj['attr'] = UpdateDomainWideFooterRequestAttr.constructFromObject(data['attr']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDomainWideFooterRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDomainWideFooterRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `attr`
        if (data['attr']) { // data not null
          UpdateDomainWideFooterRequestAttr.validateJSON(data['attr']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['items'])) {
            throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
        }

        return true;
    }


}



/**
 * @member {module:model/UpdateDomainWideFooterRequestAttr} attr
 */
UpdateDomainWideFooterRequest.prototype['attr'] = undefined;

/**
 * contains a list of domain names where you want to update the footer
 * @member {Array.<String>} items
 */
UpdateDomainWideFooterRequest.prototype['items'] = undefined;






export default UpdateDomainWideFooterRequest;

