/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateSyncJobRequestAttr from './UpdateSyncJobRequestAttr';

/**
 * The UpdateSyncJobRequest model module.
 * @module model/UpdateSyncJobRequest
 * @version 1.0.0
 */
class UpdateSyncJobRequest {
    /**
     * Constructs a new <code>UpdateSyncJobRequest</code>.
     * @alias module:model/UpdateSyncJobRequest
     */
    constructor() { 
        
        UpdateSyncJobRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateSyncJobRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateSyncJobRequest} obj Optional instance to populate.
     * @return {module:model/UpdateSyncJobRequest} The populated <code>UpdateSyncJobRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSyncJobRequest();

            if (data.hasOwnProperty('attr')) {
                obj['attr'] = UpdateSyncJobRequestAttr.constructFromObject(data['attr']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateSyncJobRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateSyncJobRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `attr`
        if (data['attr']) { // data not null
          UpdateSyncJobRequestAttr.validateJSON(data['attr']);
        }

        return true;
    }


}



/**
 * @member {module:model/UpdateSyncJobRequestAttr} attr
 */
UpdateSyncJobRequest.prototype['attr'] = undefined;

/**
 * contains list of aliases you want update
 * @member {Object} items
 */
UpdateSyncJobRequest.prototype['items'] = undefined;






export default UpdateSyncJobRequest;

