/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateDomainRequestAttr model module.
 * @module model/UpdateDomainRequestAttr
 * @version 1.0.0
 */
class UpdateDomainRequestAttr {
    /**
     * Constructs a new <code>UpdateDomainRequestAttr</code>.
     * @alias module:model/UpdateDomainRequestAttr
     */
    constructor() { 
        
        UpdateDomainRequestAttr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateDomainRequestAttr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDomainRequestAttr} obj Optional instance to populate.
     * @return {module:model/UpdateDomainRequestAttr} The populated <code>UpdateDomainRequestAttr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDomainRequestAttr();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('aliases')) {
                obj['aliases'] = ApiClient.convertToType(data['aliases'], 'Number');
            }
            if (data.hasOwnProperty('backupmx')) {
                obj['backupmx'] = ApiClient.convertToType(data['backupmx'], 'Boolean');
            }
            if (data.hasOwnProperty('defquota')) {
                obj['defquota'] = ApiClient.convertToType(data['defquota'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('gal')) {
                obj['gal'] = ApiClient.convertToType(data['gal'], 'Boolean');
            }
            if (data.hasOwnProperty('mailboxes')) {
                obj['mailboxes'] = ApiClient.convertToType(data['mailboxes'], 'Number');
            }
            if (data.hasOwnProperty('maxquota')) {
                obj['maxquota'] = ApiClient.convertToType(data['maxquota'], 'Number');
            }
            if (data.hasOwnProperty('quota')) {
                obj['quota'] = ApiClient.convertToType(data['quota'], 'Number');
            }
            if (data.hasOwnProperty('relay_all_recipients')) {
                obj['relay_all_recipients'] = ApiClient.convertToType(data['relay_all_recipients'], 'Boolean');
            }
            if (data.hasOwnProperty('relay_unknown_only')) {
                obj['relay_unknown_only'] = ApiClient.convertToType(data['relay_unknown_only'], 'Boolean');
            }
            if (data.hasOwnProperty('relayhost')) {
                obj['relayhost'] = ApiClient.convertToType(data['relayhost'], 'Number');
            }
            if (data.hasOwnProperty('rl_frame')) {
                obj['rl_frame'] = ApiClient.convertToType(data['rl_frame'], 'String');
            }
            if (data.hasOwnProperty('rl_value')) {
                obj['rl_value'] = ApiClient.convertToType(data['rl_value'], 'Number');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDomainRequestAttr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDomainRequestAttr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['rl_frame'] && !(typeof data['rl_frame'] === 'string' || data['rl_frame'] instanceof String)) {
            throw new Error("Expected the field `rl_frame` to be a primitive type in the JSON string but got " + data['rl_frame']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}



/**
 * is domain active or not
 * @member {Boolean} active
 */
UpdateDomainRequestAttr.prototype['active'] = undefined;

/**
 * limit count of aliases associated with this domain
 * @member {Number} aliases
 */
UpdateDomainRequestAttr.prototype['aliases'] = undefined;

/**
 * relay domain or not
 * @member {Boolean} backupmx
 */
UpdateDomainRequestAttr.prototype['backupmx'] = undefined;

/**
 * predefined mailbox quota in `add mailbox` form
 * @member {Number} defquota
 */
UpdateDomainRequestAttr.prototype['defquota'] = undefined;

/**
 * Description of domain
 * @member {String} description
 */
UpdateDomainRequestAttr.prototype['description'] = undefined;

/**
 * is domain global address list active or not, it enables shared contacts accross domain in SOGo webmail
 * @member {Boolean} gal
 */
UpdateDomainRequestAttr.prototype['gal'] = undefined;

/**
 * limit count of mailboxes associated with this domain
 * @member {Number} mailboxes
 */
UpdateDomainRequestAttr.prototype['mailboxes'] = undefined;

/**
 * maximum quota per mailbox
 * @member {Number} maxquota
 */
UpdateDomainRequestAttr.prototype['maxquota'] = undefined;

/**
 * maximum quota for this domain (for all mailboxes in sum)
 * @member {Number} quota
 */
UpdateDomainRequestAttr.prototype['quota'] = undefined;

/**
 * if not, them you have to create \"dummy\" mailbox for each address to relay
 * @member {Boolean} relay_all_recipients
 */
UpdateDomainRequestAttr.prototype['relay_all_recipients'] = undefined;

/**
 * Relay non-existing mailboxes only. Existing mailboxes will be delivered locally.
 * @member {Boolean} relay_unknown_only
 */
UpdateDomainRequestAttr.prototype['relay_unknown_only'] = undefined;

/**
 * id of relayhost
 * @member {Number} relayhost
 */
UpdateDomainRequestAttr.prototype['relayhost'] = undefined;

/**
 * @member {module:model/UpdateDomainRequestAttr.RlFrameEnum} rl_frame
 */
UpdateDomainRequestAttr.prototype['rl_frame'] = undefined;

/**
 * rate limit value
 * @member {Number} rl_value
 */
UpdateDomainRequestAttr.prototype['rl_value'] = undefined;

/**
 * tags for this Domain
 * @member {Array.<String>} tags
 */
UpdateDomainRequestAttr.prototype['tags'] = undefined;





/**
 * Allowed values for the <code>rl_frame</code> property.
 * @enum {String}
 * @readonly
 */
UpdateDomainRequestAttr['RlFrameEnum'] = {

    /**
     * value: "s"
     * @const
     */
    "s": "s",

    /**
     * value: "m"
     * @const
     */
    "m": "m",

    /**
     * value: "h"
     * @const
     */
    "h": "h",

    /**
     * value: "d"
     * @const
     */
    "d": "d"
};



export default UpdateDomainRequestAttr;

