/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdatePushoverSettingsRequestAttr model module.
 * @module model/UpdatePushoverSettingsRequestAttr
 * @version 1.0.0
 */
class UpdatePushoverSettingsRequestAttr {
    /**
     * Constructs a new <code>UpdatePushoverSettingsRequestAttr</code>.
     * @alias module:model/UpdatePushoverSettingsRequestAttr
     */
    constructor() { 
        
        UpdatePushoverSettingsRequestAttr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdatePushoverSettingsRequestAttr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdatePushoverSettingsRequestAttr} obj Optional instance to populate.
     * @return {module:model/UpdatePushoverSettingsRequestAttr} The populated <code>UpdatePushoverSettingsRequestAttr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatePushoverSettingsRequestAttr();

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Number');
            }
            if (data.hasOwnProperty('evaluate_x_prio')) {
                obj['evaluate_x_prio'] = ApiClient.convertToType(data['evaluate_x_prio'], 'Number');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('only_x_prio')) {
                obj['only_x_prio'] = ApiClient.convertToType(data['only_x_prio'], 'Number');
            }
            if (data.hasOwnProperty('sound')) {
                obj['sound'] = ApiClient.convertToType(data['sound'], 'String');
            }
            if (data.hasOwnProperty('senders')) {
                obj['senders'] = ApiClient.convertToType(data['senders'], 'String');
            }
            if (data.hasOwnProperty('senders_regex')) {
                obj['senders_regex'] = ApiClient.convertToType(data['senders_regex'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdatePushoverSettingsRequestAttr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdatePushoverSettingsRequestAttr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['sound'] && !(typeof data['sound'] === 'string' || data['sound'] instanceof String)) {
            throw new Error("Expected the field `sound` to be a primitive type in the JSON string but got " + data['sound']);
        }
        // ensure the json data is a string
        if (data['senders'] && !(typeof data['senders'] === 'string' || data['senders'] instanceof String)) {
            throw new Error("Expected the field `senders` to be a primitive type in the JSON string but got " + data['senders']);
        }
        // ensure the json data is a string
        if (data['senders_regex'] && !(typeof data['senders_regex'] === 'string' || data['senders_regex'] instanceof String)) {
            throw new Error("Expected the field `senders_regex` to be a primitive type in the JSON string but got " + data['senders_regex']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}



/**
 * Enables pushover 1 disable pushover 0
 * @member {Number} active
 */
UpdatePushoverSettingsRequestAttr.prototype['active'] = undefined;

/**
 * Send the Push with High priority
 * @member {Number} evaluate_x_prio
 */
UpdatePushoverSettingsRequestAttr.prototype['evaluate_x_prio'] = undefined;

/**
 * Pushover key
 * @member {String} key
 */
UpdatePushoverSettingsRequestAttr.prototype['key'] = undefined;

/**
 * Only send push for prio mails
 * @member {Number} only_x_prio
 */
UpdatePushoverSettingsRequestAttr.prototype['only_x_prio'] = undefined;

/**
 * Set notification sound
 * @member {String} sound
 */
UpdatePushoverSettingsRequestAttr.prototype['sound'] = undefined;

/**
 * Only send push for emails from these senders
 * @member {String} senders
 */
UpdatePushoverSettingsRequestAttr.prototype['senders'] = undefined;

/**
 * Regex to match senders for which a push will be send
 * @member {String} senders_regex
 */
UpdatePushoverSettingsRequestAttr.prototype['senders_regex'] = undefined;

/**
 * Custom push noficiation text
 * @member {String} text
 */
UpdatePushoverSettingsRequestAttr.prototype['text'] = undefined;

/**
 * Push title
 * @member {String} title
 */
UpdatePushoverSettingsRequestAttr.prototype['title'] = undefined;

/**
 * Pushover token
 * @member {String} token
 */
UpdatePushoverSettingsRequestAttr.prototype['token'] = undefined;






export default UpdatePushoverSettingsRequestAttr;

