/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateBCCMapRequest from '../model/CreateBCCMapRequest';
import CreateRecipientMapRequest from '../model/CreateRecipientMapRequest';
import DeleteBCCMapRequest from '../model/DeleteBCCMapRequest';
import DeleteRecipientMapRequest from '../model/DeleteRecipientMapRequest';
import InlineObject from '../model/InlineObject';

/**
* AddressRewriting service.
* @module api/AddressRewritingApi
* @version 1.0.0
*/
export default class AddressRewritingApi {

    /**
    * Constructs a new AddressRewritingApi. 
    * @alias module:api/AddressRewritingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createBCCMap operation.
     * @callback module:api/AddressRewritingApi~createBCCMapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create BCC Map
     * Using this endpoint you can create a BCC map to forward all mails via a bcc for a given domain.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateBCCMapRequest} [createBCCMapRequest] 
     * @param {module:api/AddressRewritingApi~createBCCMapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createBCCMap(opts, callback) {
      opts = opts || {};
      let postBody = opts['createBCCMapRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/bcc', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createRecipientMap operation.
     * @callback module:api/AddressRewritingApi~createRecipientMapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Recipient Map
     * Using this endpoint you can create a recipient map to forward all mails from one email address to another.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateRecipientMapRequest} [createRecipientMapRequest] 
     * @param {module:api/AddressRewritingApi~createRecipientMapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createRecipientMap(opts, callback) {
      opts = opts || {};
      let postBody = opts['createRecipientMapRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/recipient_map', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteBCCMap operation.
     * @callback module:api/AddressRewritingApi~deleteBCCMapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete BCC Map
     * Using this endpoint you can delete a BCC map, for this you have to know its ID. You can get the ID using the GET method.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteBCCMapRequest} [deleteBCCMapRequest] 
     * @param {module:api/AddressRewritingApi~deleteBCCMapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteBCCMap(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteBCCMapRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/bcc', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteRecipientMap operation.
     * @callback module:api/AddressRewritingApi~deleteRecipientMapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Recipient Map
     * Using this endpoint you can delete a recipient map, for this you have to know its ID. You can get the ID using the GET method.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteRecipientMapRequest} [deleteRecipientMapRequest] 
     * @param {module:api/AddressRewritingApi~deleteRecipientMapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteRecipientMap(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteRecipientMapRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/recipient_map', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getBCCMap operation.
     * @callback module:api/AddressRewritingApi~getBCCMapCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get BCC Map
     * Using this endpoint you can get all BCC maps.
     * @param {module:model/String} id id of entry you want to get
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/AddressRewritingApi~getBCCMapCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getBCCMap(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getBCCMap");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/bcc/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRecipientMap operation.
     * @callback module:api/AddressRewritingApi~getRecipientMapCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Recipient Map
     * Using this endpoint you can get all recipient maps.
     * @param {module:model/String} id id of entry you want to get
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/AddressRewritingApi~getRecipientMapCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getRecipientMap(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getRecipientMap");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/recipient_map/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
