/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateAppPasswordRequest from '../model/CreateAppPasswordRequest';
import DeleteAppPasswordRequest from '../model/DeleteAppPasswordRequest';
import InlineObject from '../model/InlineObject';

/**
* AppPasswords service.
* @module api/AppPasswordsApi
* @version 1.0.0
*/
export default class AppPasswordsApi {

    /**
    * Constructs a new AppPasswordsApi. 
    * @alias module:api/AppPasswordsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createAppPassword operation.
     * @callback module:api/AppPasswordsApi~createAppPasswordCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create App Password
     * Using this endpoint you can create a new app password for a specific mailbox.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateAppPasswordRequest} [createAppPasswordRequest] 
     * @param {module:api/AppPasswordsApi~createAppPasswordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createAppPassword(opts, callback) {
      opts = opts || {};
      let postBody = opts['createAppPasswordRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/app-passwd', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAppPassword operation.
     * @callback module:api/AppPasswordsApi~deleteAppPasswordCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete App Password
     * Using this endpoint you can delete a single app password.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteAppPasswordRequest} [deleteAppPasswordRequest] 
     * @param {module:api/AppPasswordsApi~deleteAppPasswordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteAppPassword(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteAppPasswordRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/app-passwd', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAppPassword operation.
     * @callback module:api/AppPasswordsApi~getAppPasswordCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get App Password
     * Using this endpoint you can get all app passwords from a specific mailbox.
     * @param {module:model/String} mailbox mailbox of entry you want to get
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/AppPasswordsApi~getAppPasswordCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAppPassword(mailbox, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'mailbox' is set
      if (mailbox === undefined || mailbox === null) {
        throw new Error("Missing the required parameter 'mailbox' when calling getAppPassword");
      }

      let pathParams = {
        'mailbox': mailbox
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/app-passwd/all/{mailbox}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
