/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EditCrossOriginResourceSharingCORSSettingsRequest from '../model/EditCrossOriginResourceSharingCORSSettingsRequest';
import InlineObject from '../model/InlineObject';

/**
* CrossOriginResourceSharingCORS service.
* @module api/CrossOriginResourceSharingCORSApi
* @version 1.0.0
*/
export default class CrossOriginResourceSharingCORSApi {

    /**
    * Constructs a new CrossOriginResourceSharingCORSApi. 
    * @alias module:api/CrossOriginResourceSharingCORSApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the editCrossOriginResourceSharingCORSSettings operation.
     * @callback module:api/CrossOriginResourceSharingCORSApi~editCrossOriginResourceSharingCORSSettingsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit Cross-Origin Resource Sharing (CORS) settings
     * This endpoint allows you to manage Cross-Origin Resource Sharing (CORS) settings for the API. CORS is a security feature implemented by web browsers to prevent unauthorized cross-origin requests. By editing the CORS settings, you can specify which domains and which methods are permitted to access the API resources from outside the mailcow domain.
     * @param {Object} opts Optional parameters
     * @param {module:model/EditCrossOriginResourceSharingCORSSettingsRequest} [editCrossOriginResourceSharingCORSSettingsRequest] 
     * @param {module:api/CrossOriginResourceSharingCORSApi~editCrossOriginResourceSharingCORSSettingsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    editCrossOriginResourceSharingCORSSettings(opts, callback) {
      opts = opts || {};
      let postBody = opts['editCrossOriginResourceSharingCORSSettingsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/edit/cors', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
