/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import DuplicateDKIMKeyRequest from '../model/DuplicateDKIMKeyRequest';
import GenerateDKIMKeyRequest from '../model/GenerateDKIMKeyRequest';
import InlineObject from '../model/InlineObject';

/**
* DKIM service.
* @module api/DKIMApi
* @version 1.0.0
*/
export default class DKIMApi {

    /**
    * Constructs a new DKIMApi. 
    * @alias module:api/DKIMApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteDKIMKey operation.
     * @callback module:api/DKIMApi~deleteDKIMKeyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete DKIM Key
     * Using this endpoint a existing DKIM Key can be deleted
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} [requestBody] 
     * @param {module:api/DKIMApi~deleteDKIMKeyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteDKIMKey(opts, callback) {
      opts = opts || {};
      let postBody = opts['requestBody'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/dkim', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the duplicateDKIMKey operation.
     * @callback module:api/DKIMApi~duplicateDKIMKeyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Duplicate DKIM Key
     * Using this endpoint you can duplicate the DKIM Key of one domain.
     * @param {Object} opts Optional parameters
     * @param {module:model/DuplicateDKIMKeyRequest} [duplicateDKIMKeyRequest] 
     * @param {module:api/DKIMApi~duplicateDKIMKeyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    duplicateDKIMKey(opts, callback) {
      opts = opts || {};
      let postBody = opts['duplicateDKIMKeyRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/dkim_duplicate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the generateDKIMKey operation.
     * @callback module:api/DKIMApi~generateDKIMKeyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate DKIM Key
     * Using this endpoint you can generate new DKIM keys.
     * @param {Object} opts Optional parameters
     * @param {module:model/GenerateDKIMKeyRequest} [generateDKIMKeyRequest] 
     * @param {module:api/DKIMApi~generateDKIMKeyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    generateDKIMKey(opts, callback) {
      opts = opts || {};
      let postBody = opts['generateDKIMKeyRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/dkim', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDKIMKey operation.
     * @callback module:api/DKIMApi~getDKIMKeyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get DKIM Key
     * Using this endpoint you can get the DKIM public key for a specific domain.
     * @param {String} domain name of domain
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/DKIMApi~getDKIMKeyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getDKIMKey(domain, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling getDKIMKey");
      }

      let pathParams = {
        'domain': domain
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/dkim/{domain}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
