/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateDomainRequest from '../model/CreateDomainRequest';
import DeleteDomainRequest from '../model/DeleteDomainRequest';
import DeleteDomainTagsRequest from '../model/DeleteDomainTagsRequest';
import InlineObject from '../model/InlineObject';
import UpdateDomainRequest from '../model/UpdateDomainRequest';
import UpdateDomainWideFooterRequest from '../model/UpdateDomainWideFooterRequest';

/**
* Domains service.
* @module api/DomainsApi
* @version 1.0.0
*/
export default class DomainsApi {

    /**
    * Constructs a new DomainsApi. 
    * @alias module:api/DomainsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createDomain operation.
     * @callback module:api/DomainsApi~createDomainCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CreateAlias200Response>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create domain
     * You may create your own domain using this action. It takes a JSON object containing a domain informations.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateDomainRequest} [createDomainRequest] 
     * @param {module:api/DomainsApi~createDomainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CreateAlias200Response>}
     */
    createDomain(opts, callback) {
      opts = opts || {};
      let postBody = opts['createDomainRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [CreateAlias200Response];
      return this.apiClient.callApi(
        '/api/v1/add/domain', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDomain operation.
     * @callback module:api/DomainsApi~deleteDomainCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CreateAlias200Response>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete domain
     * You can delete one or more domains.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteDomainRequest} [deleteDomainRequest] 
     * @param {module:api/DomainsApi~deleteDomainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CreateAlias200Response>}
     */
    deleteDomain(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteDomainRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [CreateAlias200Response];
      return this.apiClient.callApi(
        '/api/v1/delete/domain', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDomainTags operation.
     * @callback module:api/DomainsApi~deleteDomainTagsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete domain tags
     * You can delete one or more domain tags.
     * @param {String} domain name of domain
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteDomainTagsRequest} [deleteDomainTagsRequest] 
     * @param {module:api/DomainsApi~deleteDomainTagsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteDomainTags(domain, opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteDomainTagsRequest'];
      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling deleteDomainTags");
      }

      let pathParams = {
        'domain': domain
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/domain/tag/{domain}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDomains operation.
     * @callback module:api/DomainsApi~getDomainsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get domains
     * You can list all domains existing in system.
     * @param {module:model/String} id id of entry you want to get
     * @param {Object} opts Optional parameters
     * @param {String} [tags] comma seperated list of tags to filter by
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/DomainsApi~getDomainsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getDomains(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getDomains");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'tags': opts['tags']
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/domain/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateDomain operation.
     * @callback module:api/DomainsApi~updateDomainCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CreateAlias200Response>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update domain
     * You can update one or more domains per request. You can also send just attributes you want to change. Example: You can add domain names to items list and in attr object just include `\"active\": \"0\"` to deactivate domains.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateDomainRequest} [updateDomainRequest] 
     * @param {module:api/DomainsApi~updateDomainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CreateAlias200Response>}
     */
    updateDomain(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateDomainRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [CreateAlias200Response];
      return this.apiClient.callApi(
        '/api/v1/edit/domain', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateDomainWideFooter operation.
     * @callback module:api/DomainsApi~updateDomainWideFooterCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update domain wide footer
     * You can update the footer of one or more domains per request.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateDomainWideFooterRequest} [updateDomainWideFooterRequest] 
     * @param {module:api/DomainsApi~updateDomainWideFooterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    updateDomainWideFooter(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateDomainWideFooterRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/domain/footer', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
