/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateDomainPolicyRequest from '../model/CreateDomainPolicyRequest';
import DeleteDomainPolicyRequest from '../model/DeleteDomainPolicyRequest';
import InlineObject from '../model/InlineObject';

/**
* DomainAntispamPolicies service.
* @module api/DomainAntispamPoliciesApi
* @version 1.0.0
*/
export default class DomainAntispamPoliciesApi {

    /**
    * Constructs a new DomainAntispamPoliciesApi. 
    * @alias module:api/DomainAntispamPoliciesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createDomainPolicy operation.
     * @callback module:api/DomainAntispamPoliciesApi~createDomainPolicyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create domain policy
     * You may create your own domain policy using this action. It takes a JSON object containing a domain informations.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateDomainPolicyRequest} [createDomainPolicyRequest] 
     * @param {module:api/DomainAntispamPoliciesApi~createDomainPolicyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createDomainPolicy(opts, callback) {
      opts = opts || {};
      let postBody = opts['createDomainPolicyRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/domain-policy', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDomainPolicy operation.
     * @callback module:api/DomainAntispamPoliciesApi~deleteDomainPolicyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete domain policy
     * You can delete one o more domain policies.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteDomainPolicyRequest} [deleteDomainPolicyRequest] 
     * @param {module:api/DomainAntispamPoliciesApi~deleteDomainPolicyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteDomainPolicy(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteDomainPolicyRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/domain-policy', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listBlacklistDomainPolicy operation.
     * @callback module:api/DomainAntispamPoliciesApi~listBlacklistDomainPolicyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List blacklist domain policy
     * You can list all blacklist policies per domain.
     * @param {String} domain name of domain
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/DomainAntispamPoliciesApi~listBlacklistDomainPolicyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    listBlacklistDomainPolicy(domain, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling listBlacklistDomainPolicy");
      }

      let pathParams = {
        'domain': domain
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/policy_bl_domain/{domain}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listWhitelistDomainPolicy operation.
     * @callback module:api/DomainAntispamPoliciesApi~listWhitelistDomainPolicyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List whitelist domain policy
     * You can list all whitelist policies per domain.
     * @param {String} domain name of domain
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/DomainAntispamPoliciesApi~listWhitelistDomainPolicyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    listWhitelistDomainPolicy(domain, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling listWhitelistDomainPolicy");
      }

      let pathParams = {
        'domain': domain
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/policy_wl_domain/{domain}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
