/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateDomainAdminUserRequest from '../model/CreateDomainAdminUserRequest';
import DeleteDomainAdminRequest from '../model/DeleteDomainAdminRequest';
import EditDomainAdminACLRequest from '../model/EditDomainAdminACLRequest';
import EditDomainAdminUserRequest from '../model/EditDomainAdminUserRequest';
import InlineObject from '../model/InlineObject';

/**
* DomainAdmin service.
* @module api/DomainAdminApi
* @version 1.0.0
*/
export default class DomainAdminApi {

    /**
    * Constructs a new DomainAdminApi. 
    * @alias module:api/DomainAdminApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createDomainAdminUser operation.
     * @callback module:api/DomainAdminApi~createDomainAdminUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Domain Admin user
     * Using this endpoint you can create a new Domain Admin user. This user has full control over a domain, and can create new mailboxes and aliases.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateDomainAdminUserRequest} [createDomainAdminUserRequest] 
     * @param {module:api/DomainAdminApi~createDomainAdminUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createDomainAdminUser(opts, callback) {
      opts = opts || {};
      let postBody = opts['createDomainAdminUserRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/domain-admin', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDomainAdmin operation.
     * @callback module:api/DomainAdminApi~deleteDomainAdminCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Domain Admin
     * Using this endpoint a existing Domain Admin user can be deleted.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteDomainAdminRequest} [deleteDomainAdminRequest] 
     * @param {module:api/DomainAdminApi~deleteDomainAdminCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteDomainAdmin(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteDomainAdminRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/domain-admin', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the editDomainAdminACL operation.
     * @callback module:api/DomainAdminApi~editDomainAdminACLCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit Domain Admin ACL
     * Using this endpoint you can edit the ACLs of a Domain Admin user. This user has full control over a domain, and can create new mailboxes and aliases.
     * @param {Object} opts Optional parameters
     * @param {module:model/EditDomainAdminACLRequest} [editDomainAdminACLRequest] 
     * @param {module:api/DomainAdminApi~editDomainAdminACLCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    editDomainAdminACL(opts, callback) {
      opts = opts || {};
      let postBody = opts['editDomainAdminACLRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/da-acl', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the editDomainAdminUser operation.
     * @callback module:api/DomainAdminApi~editDomainAdminUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit Domain Admin user
     * Using this endpoint you can edit a existing Domain Admin user. This user has full control over a domain, and can create new mailboxes and aliases.
     * @param {Object} opts Optional parameters
     * @param {module:model/EditDomainAdminUserRequest} [editDomainAdminUserRequest] 
     * @param {module:api/DomainAdminApi~editDomainAdminUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    editDomainAdminUser(opts, callback) {
      opts = opts || {};
      let postBody = opts['editDomainAdminUserRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/domain-admin', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDomainAdmins operation.
     * @callback module:api/DomainAdminApi~getDomainAdminsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Domain Admins
     * 
     * @param {module:api/DomainAdminApi~getDomainAdminsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getDomainAdmins(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/domain-admin/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
