/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import EditFail2BanRequest from '../model/EditFail2BanRequest';
import InlineObject from '../model/InlineObject';

/**
* Fail2Ban service.
* @module api/Fail2BanApi
* @version 1.0.0
*/
export default class Fail2BanApi {

    /**
    * Constructs a new Fail2BanApi. 
    * @alias module:api/Fail2BanApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the editFail2Ban operation.
     * @callback module:api/Fail2BanApi~editFail2BanCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit Fail2Ban
     * Using this endpoint you can edit the Fail2Ban config and black or whitelist new ips.
     * @param {Object} opts Optional parameters
     * @param {module:model/EditFail2BanRequest} [editFail2BanRequest] 
     * @param {module:api/Fail2BanApi~editFail2BanCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    editFail2Ban(opts, callback) {
      opts = opts || {};
      let postBody = opts['editFail2BanRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', '*/*'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/fail2ban', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFail2BanConfig operation.
     * @callback module:api/Fail2BanApi~getFail2BanConfigCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Fail2Ban Config
     * Gets the current Fail2Ban configuration.
     * @param {module:api/Fail2BanApi~getFail2BanConfigCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getFail2BanConfig(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/fail2ban', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
