/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EditExternalIdentityProviderSettingsRequest from '../model/EditExternalIdentityProviderSettingsRequest';
import InlineObject from '../model/InlineObject';

/**
* IdentityProvider service.
* @module api/IdentityProviderApi
* @version 1.0.0
*/
export default class IdentityProviderApi {

    /**
    * Constructs a new IdentityProviderApi. 
    * @alias module:api/IdentityProviderApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the editExternalIdentityProviderSettings operation.
     * @callback module:api/IdentityProviderApi~editExternalIdentityProviderSettingsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit external Identity Provider
     * Configure an external Identity Provider to use as user authentication
     * @param {Object} opts Optional parameters
     * @param {module:model/EditExternalIdentityProviderSettingsRequest} [editExternalIdentityProviderSettingsRequest] 
     * @param {module:api/IdentityProviderApi~editExternalIdentityProviderSettingsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    editExternalIdentityProviderSettings(opts, callback) {
      opts = opts || {};
      let postBody = opts['editExternalIdentityProviderSettingsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/edit/identity-provider', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
