/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject from '../model/InlineObject';

/**
* Logs service.
* @module api/LogsApi
* @version 1.0.0
*/
export default class LogsApi {

    /**
    * Constructs a new LogsApi. 
    * @alias module:api/LogsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getACMELogs operation.
     * @callback module:api/LogsApi~getACMELogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get ACME logs
     * This Api endpoint lists all ACME logs from issued Lets Enctypts certificates. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getACMELogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getACMELogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getACMELogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/acme/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiLogs operation.
     * @callback module:api/LogsApi~getApiLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Api logs
     * This Api endpoint lists all Api logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getApiLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getApiLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getApiLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/api/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAutodiscoverLogs operation.
     * @callback module:api/LogsApi~getAutodiscoverLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Autodiscover logs
     * This Api endpoint lists all Autodiscover logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getAutodiscoverLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAutodiscoverLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getAutodiscoverLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/autodiscover/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDovecotLogs operation.
     * @callback module:api/LogsApi~getDovecotLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Dovecot logs
     * This Api endpoint lists all Dovecot logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getDovecotLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getDovecotLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getDovecotLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/dovecot/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getNetfilterLogs operation.
     * @callback module:api/LogsApi~getNetfilterLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Netfilter logs
     * This Api endpoint lists all Netfilter logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getNetfilterLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getNetfilterLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getNetfilterLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/netfilter/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPostfixLogs operation.
     * @callback module:api/LogsApi~getPostfixLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Postfix logs
     * This Api endpoint lists all Postfix logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getPostfixLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getPostfixLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getPostfixLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/postfix/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRatelimitLogs operation.
     * @callback module:api/LogsApi~getRatelimitLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Ratelimit logs
     * This Api endpoint lists all Ratelimit logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getRatelimitLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getRatelimitLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getRatelimitLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/ratelimited/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRspamdLogs operation.
     * @callback module:api/LogsApi~getRspamdLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Rspamd logs
     * This Api endpoint lists all Rspamd logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getRspamdLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getRspamdLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getRspamdLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/rspamd-history/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSOGoLogs operation.
     * @callback module:api/LogsApi~getSOGoLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get SOGo logs
     * This Api endpoint lists all SOGo logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getSOGoLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getSOGoLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getSOGoLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/sogo/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getWatchdogLogs operation.
     * @callback module:api/LogsApi~getWatchdogLogsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Watchdog logs
     * This Api endpoint lists all Watchdog logs. Tip: You can limit how many logs you want to get by using `/<count>` at the end of the api url.
     * @param {Number} count Number of logs to return
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/LogsApi~getWatchdogLogsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getWatchdogLogs(count, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'count' is set
      if (count === undefined || count === null) {
        throw new Error("Missing the required parameter 'count' when calling getWatchdogLogs");
      }

      let pathParams = {
        'count': count
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/logs/watchdog/{count}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
