/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateMailboxRequest from '../model/CreateMailboxRequest';
import DeleteMailboxRequest from '../model/DeleteMailboxRequest';
import DeleteMailboxTagsRequest from '../model/DeleteMailboxTagsRequest';
import InlineObject from '../model/InlineObject';
import QuarantineNotificationsRequest from '../model/QuarantineNotificationsRequest';
import UpdateMailboxACLRequest from '../model/UpdateMailboxACLRequest';
import UpdateMailboxCustomAttributesRequest from '../model/UpdateMailboxCustomAttributesRequest';
import UpdateMailboxRequest from '../model/UpdateMailboxRequest';
import UpdatePushoverSettingsRequest from '../model/UpdatePushoverSettingsRequest';

/**
* Mailboxes service.
* @module api/MailboxesApi
* @version 1.0.0
*/
export default class MailboxesApi {

    /**
    * Constructs a new MailboxesApi. 
    * @alias module:api/MailboxesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createMailbox operation.
     * @callback module:api/MailboxesApi~createMailboxCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create mailbox
     * You may create your own mailbox using this action. It takes a JSON object containing a domain informations.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateMailboxRequest} [createMailboxRequest] 
     * @param {module:api/MailboxesApi~createMailboxCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createMailbox(opts, callback) {
      opts = opts || {};
      let postBody = opts['createMailboxRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/mailbox', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteMailbox operation.
     * @callback module:api/MailboxesApi~deleteMailboxCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete mailbox
     * You can delete one or more mailboxes.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteMailboxRequest} [deleteMailboxRequest] 
     * @param {module:api/MailboxesApi~deleteMailboxCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteMailbox(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteMailboxRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/mailbox', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteMailboxTags operation.
     * @callback module:api/MailboxesApi~deleteMailboxTagsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete mailbox tags
     * You can delete one or more mailbox tags.
     * @param {String} mailbox name of mailbox
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteMailboxTagsRequest} [deleteMailboxTagsRequest] 
     * @param {module:api/MailboxesApi~deleteMailboxTagsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteMailboxTags(mailbox, opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteMailboxTagsRequest'];
      // verify the required parameter 'mailbox' is set
      if (mailbox === undefined || mailbox === null) {
        throw new Error("Missing the required parameter 'mailbox' when calling deleteMailboxTags");
      }

      let pathParams = {
        'mailbox': mailbox
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/mailbox/tag/{mailbox}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the editMailboxSpamFilterScore operation.
     * @callback module:api/MailboxesApi~editMailboxSpamFilterScoreCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit mailbox spam filter score
     * Using this endpoint you can edit the spam filter score for a certain mailbox.
     * @param {Object} opts Optional parameters
     * @param {Object} [body] 
     * @param {module:api/MailboxesApi~editMailboxSpamFilterScoreCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    editMailboxSpamFilterScore(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/spam-score/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMailboxOrGlobalSpamFilterScore operation.
     * @callback module:api/MailboxesApi~getMailboxOrGlobalSpamFilterScoreCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get mailbox or global spam filter score
     * Using this endpoint you can get the global spam filter score or the spam filter score of a certain mailbox.
     * @param {String} mailbox name of mailbox or empty for current user - admin user will retrieve the global spam filter score
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/MailboxesApi~getMailboxOrGlobalSpamFilterScoreCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getMailboxOrGlobalSpamFilterScore(mailbox, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'mailbox' is set
      if (mailbox === undefined || mailbox === null) {
        throw new Error("Missing the required parameter 'mailbox' when calling getMailboxOrGlobalSpamFilterScore");
      }

      let pathParams = {
        'mailbox': mailbox
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/spam-score/{mailbox}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMailboxes operation.
     * @callback module:api/MailboxesApi~getMailboxesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get mailboxes
     * You can list all mailboxes existing in system.
     * @param {module:model/String} id id of entry you want to get
     * @param {Object} opts Optional parameters
     * @param {String} [tags] comma seperated list of tags to filter by
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/MailboxesApi~getMailboxesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getMailboxes(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getMailboxes");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'tags': opts['tags']
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/mailbox/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMailboxesOfADomain operation.
     * @callback module:api/MailboxesApi~getMailboxesOfADomainCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get mailboxes of a domain
     * You can list all mailboxes existing in system for a specific domain.
     * @param {String} domain name of domain
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/MailboxesApi~getMailboxesOfADomainCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getMailboxesOfADomain(domain, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling getMailboxesOfADomain");
      }

      let pathParams = {
        'domain': domain
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/mailbox/all/{domain}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the quarantineNotifications operation.
     * @callback module:api/MailboxesApi~quarantineNotificationsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Quarantine Notifications
     * You can update one or more mailboxes per request.
     * @param {Object} opts Optional parameters
     * @param {module:model/QuarantineNotificationsRequest} [quarantineNotificationsRequest] 
     * @param {module:api/MailboxesApi~quarantineNotificationsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    quarantineNotifications(opts, callback) {
      opts = opts || {};
      let postBody = opts['quarantineNotificationsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/edit/quarantine_notification', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateMailbox operation.
     * @callback module:api/MailboxesApi~updateMailboxCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update mailbox
     * You can update one or more mailboxes per request. You can also send just attributes you want to change
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateMailboxRequest} [updateMailboxRequest] 
     * @param {module:api/MailboxesApi~updateMailboxCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    updateMailbox(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateMailboxRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/mailbox', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateMailboxACL operation.
     * @callback module:api/MailboxesApi~updateMailboxACLCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update mailbox ACL
     * Using this endpoints its possible to update the ACL's for mailboxes
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateMailboxACLRequest} [updateMailboxACLRequest] 
     * @param {module:api/MailboxesApi~updateMailboxACLCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    updateMailboxACL(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateMailboxACLRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/user-acl', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateMailboxCustomAttributes operation.
     * @callback module:api/MailboxesApi~updateMailboxCustomAttributesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update mailbox custom attributes
     * You can update custom attributes of one or more mailboxes per request.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateMailboxCustomAttributesRequest} [updateMailboxCustomAttributesRequest] 
     * @param {module:api/MailboxesApi~updateMailboxCustomAttributesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    updateMailboxCustomAttributes(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateMailboxCustomAttributesRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/mailbox/custom-attribute', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePushoverSettings operation.
     * @callback module:api/MailboxesApi~updatePushoverSettingsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Pushover settings
     * Using this endpoint it is possible to update the pushover settings for mailboxes
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdatePushoverSettingsRequest} [updatePushoverSettingsRequest] 
     * @param {module:api/MailboxesApi~updatePushoverSettingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    updatePushoverSettings(opts, callback) {
      opts = opts || {};
      let postBody = opts['updatePushoverSettingsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/pushover', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
