/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateOAuthClientRequest from '../model/CreateOAuthClientRequest';
import DeleteOAuthClientRequest from '../model/DeleteOAuthClientRequest';
import InlineObject from '../model/InlineObject';

/**
* OAuthClients service.
* @module api/OAuthClientsApi
* @version 1.0.0
*/
export default class OAuthClientsApi {

    /**
    * Constructs a new OAuthClientsApi. 
    * @alias module:api/OAuthClientsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createOAuthClient operation.
     * @callback module:api/OAuthClientsApi~createOAuthClientCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create oAuth Client
     * Using this endpoint you can create a oAuth clients.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOAuthClientRequest} [createOAuthClientRequest] 
     * @param {module:api/OAuthClientsApi~createOAuthClientCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createOAuthClient(opts, callback) {
      opts = opts || {};
      let postBody = opts['createOAuthClientRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/oauth2-client', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteOAuthClient operation.
     * @callback module:api/OAuthClientsApi~deleteOAuthClientCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete oAuth Client
     * Using this endpoint you can delete a oAuth client, for this you have to know its ID. You can get the ID using the GET method.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteOAuthClientRequest} [deleteOAuthClientRequest] 
     * @param {module:api/OAuthClientsApi~deleteOAuthClientCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteOAuthClient(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteOAuthClientRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/oauth2-client', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOAuthClients operation.
     * @callback module:api/OAuthClientsApi~getOAuthClientsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get oAuth Clients
     * Using this endpoint you can get all oAuth clients.
     * @param {module:model/String} id id of entry you want to get
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/OAuthClientsApi~getOAuthClientsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getOAuthClients(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getOAuthClients");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/oauth2-client/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
