/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateTLSPolicyMapRequest from '../model/CreateTLSPolicyMapRequest';
import DeleteTLSPolicyMapRequest from '../model/DeleteTLSPolicyMapRequest';
import InlineObject from '../model/InlineObject';

/**
* OutgoingTLSPolicyMapOverrides service.
* @module api/OutgoingTLSPolicyMapOverridesApi
* @version 1.0.0
*/
export default class OutgoingTLSPolicyMapOverridesApi {

    /**
    * Constructs a new OutgoingTLSPolicyMapOverridesApi. 
    * @alias module:api/OutgoingTLSPolicyMapOverridesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createTLSPolicyMap operation.
     * @callback module:api/OutgoingTLSPolicyMapOverridesApi~createTLSPolicyMapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create TLS Policy Map
     * Using this endpoint you can create a TLS policy map override.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateTLSPolicyMapRequest} [createTLSPolicyMapRequest] 
     * @param {module:api/OutgoingTLSPolicyMapOverridesApi~createTLSPolicyMapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createTLSPolicyMap(opts, callback) {
      opts = opts || {};
      let postBody = opts['createTLSPolicyMapRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/tls-policy-map', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTLSPolicyMap operation.
     * @callback module:api/OutgoingTLSPolicyMapOverridesApi~deleteTLSPolicyMapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete TLS Policy Map
     * Using this endpoint you can delete a TLS Policy Map, for this you have to know its ID. You can get the ID using the GET method.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteTLSPolicyMapRequest} [deleteTLSPolicyMapRequest] 
     * @param {module:api/OutgoingTLSPolicyMapOverridesApi~deleteTLSPolicyMapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteTLSPolicyMap(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteTLSPolicyMapRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/tls-policy-map', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTLSPolicyMap operation.
     * @callback module:api/OutgoingTLSPolicyMapOverridesApi~getTLSPolicyMapCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get TLS Policy Map
     * Using this endpoint you can get all TLS policy map override maps.
     * @param {module:model/String} id id of entry you want to get
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/OutgoingTLSPolicyMapOverridesApi~getTLSPolicyMapCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getTLSPolicyMap(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTLSPolicyMap");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/tls-policy-map/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
