/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DeleteQueueRequest from '../model/DeleteQueueRequest';
import FlushQueueRequest from '../model/FlushQueueRequest';
import InlineObject from '../model/InlineObject';

/**
* QueueManager service.
* @module api/QueueManagerApi
* @version 1.0.0
*/
export default class QueueManagerApi {

    /**
    * Constructs a new QueueManagerApi. 
    * @alias module:api/QueueManagerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteQueue operation.
     * @callback module:api/QueueManagerApi~deleteQueueCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Queue
     * Using this API you can delete the current mail queue. This will delete all mails in it. This API uses the command: `postsuper -d`
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteQueueRequest} [deleteQueueRequest] 
     * @param {module:api/QueueManagerApi~deleteQueueCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteQueue(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteQueueRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/delete/mailq', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the flushQueue operation.
     * @callback module:api/QueueManagerApi~flushQueueCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Flush Queue
     * Using this API you can flush the current mail queue. This will try to deliver all mails currently in it. This API uses the command: `postqueue -f`
     * @param {Object} opts Optional parameters
     * @param {module:model/FlushQueueRequest} [flushQueueRequest] 
     * @param {module:api/QueueManagerApi~flushQueueCallback} callback The callback function, accepting three arguments: error, data, response
     */
    flushQueue(opts, callback) {
      opts = opts || {};
      let postBody = opts['flushQueueRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/edit/mailq', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getQueue operation.
     * @callback module:api/QueueManagerApi~getQueueCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Queue
     * Get the current mail queue and everything it contains.
     * @param {module:api/QueueManagerApi~getQueueCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getQueue(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/mailq/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
