/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import EditDomainRatelimitsRequest from '../model/EditDomainRatelimitsRequest';
import EditMailboxRatelimitsRequest from '../model/EditMailboxRatelimitsRequest';
import InlineObject from '../model/InlineObject';

/**
* Ratelimits service.
* @module api/RatelimitsApi
* @version 1.0.0
*/
export default class RatelimitsApi {

    /**
    * Constructs a new RatelimitsApi. 
    * @alias module:api/RatelimitsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the editDomainRatelimits operation.
     * @callback module:api/RatelimitsApi~editDomainRatelimitsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit domain ratelimits
     * Using this endpoint you can edit the ratelimits for a certain domains.
     * @param {Object} opts Optional parameters
     * @param {module:model/EditDomainRatelimitsRequest} [editDomainRatelimitsRequest] 
     * @param {module:api/RatelimitsApi~editDomainRatelimitsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    editDomainRatelimits(opts, callback) {
      opts = opts || {};
      let postBody = opts['editDomainRatelimitsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/rl-domain/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the editMailboxRatelimits operation.
     * @callback module:api/RatelimitsApi~editMailboxRatelimitsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit mailbox ratelimits
     * Using this endpoint you can edit the ratelimits for a certain mailbox.
     * @param {Object} opts Optional parameters
     * @param {module:model/EditMailboxRatelimitsRequest} [editMailboxRatelimitsRequest] 
     * @param {module:api/RatelimitsApi~editMailboxRatelimitsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    editMailboxRatelimits(opts, callback) {
      opts = opts || {};
      let postBody = opts['editMailboxRatelimitsRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/rl-mbox/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDomainRatelimits operation.
     * @callback module:api/RatelimitsApi~getDomainRatelimitsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get domain ratelimits
     * Using this endpoint you can get the ratelimits for a certain domains. You can use all for all domain.
     * @param {String} domain name of domain or all
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/RatelimitsApi~getDomainRatelimitsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getDomainRatelimits(domain, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling getDomainRatelimits");
      }

      let pathParams = {
        'domain': domain
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/rl-domain/{domain}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMailboxRatelimits operation.
     * @callback module:api/RatelimitsApi~getMailboxRatelimitsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get mailbox ratelimits
     * Using this endpoint you can get the ratelimits for a certain mailbox. You can use all for all mailboxes.
     * @param {String} mailbox name of mailbox or all
     * @param {Object} opts Optional parameters
     * @param {String} [xAPIKey] e.g. api-key-string
     * @param {module:api/RatelimitsApi~getMailboxRatelimitsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getMailboxRatelimits(mailbox, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'mailbox' is set
      if (mailbox === undefined || mailbox === null) {
        throw new Error("Missing the required parameter 'mailbox' when calling getMailboxRatelimits");
      }

      let pathParams = {
        'mailbox': mailbox
      };
      let queryParams = {
      };
      let headerParams = {
        'X-API-Key': opts['xAPIKey']
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/rl-mbox/{mailbox}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
