/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateResourcesRequest from '../model/CreateResourcesRequest';
import DeleteResourcesRequest from '../model/DeleteResourcesRequest';
import InlineObject from '../model/InlineObject';

/**
* Resources service.
* @module api/ResourcesApi
* @version 1.0.0
*/
export default class ResourcesApi {

    /**
    * Constructs a new ResourcesApi. 
    * @alias module:api/ResourcesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createResources operation.
     * @callback module:api/ResourcesApi~createResourcesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Resources
     * Using this endpoint you can create Resources.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateResourcesRequest} [createResourcesRequest] 
     * @param {module:api/ResourcesApi~createResourcesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createResources(opts, callback) {
      opts = opts || {};
      let postBody = opts['createResourcesRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/resource', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteResources operation.
     * @callback module:api/ResourcesApi~deleteResourcesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Resources
     * Using this endpoint you can delete a Resources, for this you have to know its ID. You can get the ID using the GET method.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteResourcesRequest} [deleteResourcesRequest] 
     * @param {module:api/ResourcesApi~deleteResourcesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteResources(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteResourcesRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/resource', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getResources operation.
     * @callback module:api/ResourcesApi~getResourcesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Resources
     * Using this endpoint you can get all Resources.
     * @param {module:api/ResourcesApi~getResourcesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getResources(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/resource/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
