/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateAlias200Response from '../model/CreateAlias200Response';
import CreateSyncJobRequest from '../model/CreateSyncJobRequest';
import DeleteSyncJobRequest from '../model/DeleteSyncJobRequest';
import InlineObject from '../model/InlineObject';
import UpdateSyncJobRequest from '../model/UpdateSyncJobRequest';

/**
* SyncJobs service.
* @module api/SyncJobsApi
* @version 1.0.0
*/
export default class SyncJobsApi {

    /**
    * Constructs a new SyncJobsApi. 
    * @alias module:api/SyncJobsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createSyncJob operation.
     * @callback module:api/SyncJobsApi~createSyncJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create sync job
     * You can create new sync job using this action. It takes a JSON object containing a domain informations.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateSyncJobRequest} [createSyncJobRequest] 
     * @param {module:api/SyncJobsApi~createSyncJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    createSyncJob(opts, callback) {
      opts = opts || {};
      let postBody = opts['createSyncJobRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/add/syncjob', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteSyncJob operation.
     * @callback module:api/SyncJobsApi~deleteSyncJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete sync job
     * You can delete one or more sync jobs.
     * @param {Object} opts Optional parameters
     * @param {module:model/DeleteSyncJobRequest} [deleteSyncJobRequest] 
     * @param {module:api/SyncJobsApi~deleteSyncJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    deleteSyncJob(opts, callback) {
      opts = opts || {};
      let postBody = opts['deleteSyncJobRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/delete/syncjob', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSyncJobs operation.
     * @callback module:api/SyncJobsApi~getSyncJobsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get sync jobs
     * You can list all syn jobs existing in system.
     * @param {module:api/SyncJobsApi~getSyncJobsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getSyncJobs(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/get/syncjobs/all/no_log', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSyncJob operation.
     * @callback module:api/SyncJobsApi~updateSyncJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlias200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update sync job
     * You can update one or more sync jobs per request. You can also send just attributes you want to change.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateSyncJobRequest} [updateSyncJobRequest] 
     * @param {module:api/SyncJobsApi~updateSyncJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlias200Response}
     */
    updateSyncJob(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateSyncJobRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlias200Response;
      return this.apiClient.callApi(
        '/api/v1/edit/syncjob', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
