/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailcowSdkJs);
  }
}(this, function(expect, MailcowSdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateMailboxRequestAttr', function() {
    it('should create an instance of UpdateMailboxRequestAttr', function() {
      // uncomment below and update the code to test UpdateMailboxRequestAttr
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be.a(MailcowSdkJs.UpdateMailboxRequestAttr);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property forcePwUpdate (base name: "force_pw_update")', function() {
      // uncomment below and update the code to test the property forcePwUpdate
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property authsource (base name: "authsource")', function() {
      // uncomment below and update the code to test the property authsource
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property password2 (base name: "password2")', function() {
      // uncomment below and update the code to test the property password2
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property quota (base name: "quota")', function() {
      // uncomment below and update the code to test the property quota
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property senderAcl (base name: "sender_acl")', function() {
      // uncomment below and update the code to test the property senderAcl
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property sogoAccess (base name: "sogo_access")', function() {
      // uncomment below and update the code to test the property sogoAccess
      //var instance = new MailcowSdkJs.UpdateMailboxRequestAttr();
      //expect(instance).to.be();
    });

  });

}));
