/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailcowSdkJs);
  }
}(this, function(expect, MailcowSdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdatePushoverSettingsRequestAttr', function() {
    it('should create an instance of UpdatePushoverSettingsRequestAttr', function() {
      // uncomment below and update the code to test UpdatePushoverSettingsRequestAttr
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be.a(MailcowSdkJs.UpdatePushoverSettingsRequestAttr);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property evaluateXPrio (base name: "evaluate_x_prio")', function() {
      // uncomment below and update the code to test the property evaluateXPrio
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property onlyXPrio (base name: "only_x_prio")', function() {
      // uncomment below and update the code to test the property onlyXPrio
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property sound (base name: "sound")', function() {
      // uncomment below and update the code to test the property sound
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property senders (base name: "senders")', function() {
      // uncomment below and update the code to test the property senders
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property sendersRegex (base name: "senders_regex")', function() {
      // uncomment below and update the code to test the property sendersRegex
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new MailcowSdkJs.UpdatePushoverSettingsRequestAttr();
      //expect(instance).to.be();
    });

  });

}));
