/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailcowSdkJs);
  }
}(this, function(expect, MailcowSdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailcowSdkJs.UpdateDomainRequestAttr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateDomainRequestAttr', function() {
    it('should create an instance of UpdateDomainRequestAttr', function() {
      // uncomment below and update the code to test UpdateDomainRequestAttr
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be.a(MailcowSdkJs.UpdateDomainRequestAttr);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property aliases (base name: "aliases")', function() {
      // uncomment below and update the code to test the property aliases
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property backupmx (base name: "backupmx")', function() {
      // uncomment below and update the code to test the property backupmx
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property defquota (base name: "defquota")', function() {
      // uncomment below and update the code to test the property defquota
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property gal (base name: "gal")', function() {
      // uncomment below and update the code to test the property gal
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property mailboxes (base name: "mailboxes")', function() {
      // uncomment below and update the code to test the property mailboxes
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property maxquota (base name: "maxquota")', function() {
      // uncomment below and update the code to test the property maxquota
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property quota (base name: "quota")', function() {
      // uncomment below and update the code to test the property quota
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property relayAllRecipients (base name: "relay_all_recipients")', function() {
      // uncomment below and update the code to test the property relayAllRecipients
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property relayUnknownOnly (base name: "relay_unknown_only")', function() {
      // uncomment below and update the code to test the property relayUnknownOnly
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property relayhost (base name: "relayhost")', function() {
      // uncomment below and update the code to test the property relayhost
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property rlFrame (base name: "rl_frame")', function() {
      // uncomment below and update the code to test the property rlFrame
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property rlValue (base name: "rl_value")', function() {
      // uncomment below and update the code to test the property rlValue
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new MailcowSdkJs.UpdateDomainRequestAttr();
      //expect(instance).to.be();
    });

  });

}));
