/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailcowSdkJs);
  }
}(this, function(expect, MailcowSdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateSyncJobRequestAttr', function() {
    it('should create an instance of UpdateSyncJobRequestAttr', function() {
      // uncomment below and update the code to test UpdateSyncJobRequestAttr
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be.a(MailcowSdkJs.UpdateSyncJobRequestAttr);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property automap (base name: "automap")', function() {
      // uncomment below and update the code to test the property automap
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property customParams (base name: "custom_params")', function() {
      // uncomment below and update the code to test the property customParams
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property delete1 (base name: "delete1")', function() {
      // uncomment below and update the code to test the property delete1
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property delete2 (base name: "delete2")', function() {
      // uncomment below and update the code to test the property delete2
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property delete2duplicates (base name: "delete2duplicates")', function() {
      // uncomment below and update the code to test the property delete2duplicates
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property enc1 (base name: "enc1")', function() {
      // uncomment below and update the code to test the property enc1
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property exclude (base name: "exclude")', function() {
      // uncomment below and update the code to test the property exclude
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property host1 (base name: "host1")', function() {
      // uncomment below and update the code to test the property host1
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property maxage (base name: "maxage")', function() {
      // uncomment below and update the code to test the property maxage
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property maxbytespersecond (base name: "maxbytespersecond")', function() {
      // uncomment below and update the code to test the property maxbytespersecond
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property minsInterval (base name: "mins_interval")', function() {
      // uncomment below and update the code to test the property minsInterval
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property password1 (base name: "password1")', function() {
      // uncomment below and update the code to test the property password1
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property port1 (base name: "port1")', function() {
      // uncomment below and update the code to test the property port1
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property skipcrossduplicates (base name: "skipcrossduplicates")', function() {
      // uncomment below and update the code to test the property skipcrossduplicates
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property subfolder2 (base name: "subfolder2")', function() {
      // uncomment below and update the code to test the property subfolder2
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property subscribeall (base name: "subscribeall")', function() {
      // uncomment below and update the code to test the property subscribeall
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property timeout1 (base name: "timeout1")', function() {
      // uncomment below and update the code to test the property timeout1
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property timeout2 (base name: "timeout2")', function() {
      // uncomment below and update the code to test the property timeout2
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

    it('should have the property user1 (base name: "user1")', function() {
      // uncomment below and update the code to test the property user1
      //var instance = new MailcowSdkJs.UpdateSyncJobRequestAttr();
      //expect(instance).to.be();
    });

  });

}));
