/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddForwardHostRequest from './model/AddForwardHostRequest';
import CreateAlias200Response from './model/CreateAlias200Response';
import CreateAliasRequest from './model/CreateAliasRequest';
import CreateAppPasswordRequest from './model/CreateAppPasswordRequest';
import CreateBCCMapRequest from './model/CreateBCCMapRequest';
import CreateDomainAdminUserRequest from './model/CreateDomainAdminUserRequest';
import CreateDomainPolicyRequest from './model/CreateDomainPolicyRequest';
import CreateDomainRequest from './model/CreateDomainRequest';
import CreateMailboxRequest from './model/CreateMailboxRequest';
import CreateOAuthClientRequest from './model/CreateOAuthClientRequest';
import CreateRecipientMapRequest from './model/CreateRecipientMapRequest';
import CreateResourcesRequest from './model/CreateResourcesRequest';
import CreateSenderDependentTransportsRequest from './model/CreateSenderDependentTransportsRequest';
import CreateSyncJobRequest from './model/CreateSyncJobRequest';
import CreateTLSPolicyMapRequest from './model/CreateTLSPolicyMapRequest';
import CreateTimeLimitedAliasRequest from './model/CreateTimeLimitedAliasRequest';
import CreateTransportMapsRequest from './model/CreateTransportMapsRequest';
import DeleteAppPasswordRequest from './model/DeleteAppPasswordRequest';
import DeleteBCCMapRequest from './model/DeleteBCCMapRequest';
import DeleteDomainAdminRequest from './model/DeleteDomainAdminRequest';
import DeleteDomainPolicyRequest from './model/DeleteDomainPolicyRequest';
import DeleteDomainRequest from './model/DeleteDomainRequest';
import DeleteDomainTagsRequest from './model/DeleteDomainTagsRequest';
import DeleteForwardHostRequest from './model/DeleteForwardHostRequest';
import DeleteMailboxRequest from './model/DeleteMailboxRequest';
import DeleteMailboxTagsRequest from './model/DeleteMailboxTagsRequest';
import DeleteMailsInQuarantineRequest from './model/DeleteMailsInQuarantineRequest';
import DeleteOAuthClientRequest from './model/DeleteOAuthClientRequest';
import DeleteQueueRequest from './model/DeleteQueueRequest';
import DeleteRecipientMapRequest from './model/DeleteRecipientMapRequest';
import DeleteResourcesRequest from './model/DeleteResourcesRequest';
import DeleteSenderDependentTransportsRequest from './model/DeleteSenderDependentTransportsRequest';
import DeleteSyncJobRequest from './model/DeleteSyncJobRequest';
import DeleteTLSPolicyMapRequest from './model/DeleteTLSPolicyMapRequest';
import DeleteTransportMapsRequest from './model/DeleteTransportMapsRequest';
import DuplicateDKIMKeyRequest from './model/DuplicateDKIMKeyRequest';
import EditCrossOriginResourceSharingCORSSettingsRequest from './model/EditCrossOriginResourceSharingCORSSettingsRequest';
import EditCrossOriginResourceSharingCORSSettingsRequestAttr from './model/EditCrossOriginResourceSharingCORSSettingsRequestAttr';
import EditDomainAdminACLRequest from './model/EditDomainAdminACLRequest';
import EditDomainAdminACLRequestAttr from './model/EditDomainAdminACLRequestAttr';
import EditDomainAdminUserRequest from './model/EditDomainAdminUserRequest';
import EditDomainAdminUserRequestAttr from './model/EditDomainAdminUserRequestAttr';
import EditDomainRatelimitsRequest from './model/EditDomainRatelimitsRequest';
import EditExternalIdentityProviderSettingsRequest from './model/EditExternalIdentityProviderSettingsRequest';
import EditExternalIdentityProviderSettingsRequestAttr from './model/EditExternalIdentityProviderSettingsRequestAttr';
import EditFail2BanRequest from './model/EditFail2BanRequest';
import EditFail2BanRequestAttr from './model/EditFail2BanRequestAttr';
import EditMailboxRatelimitsRequest from './model/EditMailboxRatelimitsRequest';
import EditMailboxRatelimitsRequestAttr from './model/EditMailboxRatelimitsRequestAttr';
import FlushQueueRequest from './model/FlushQueueRequest';
import GenerateDKIMKeyRequest from './model/GenerateDKIMKeyRequest';
import InlineObject from './model/InlineObject';
import IssueDomainAdminSSOTokenRequest from './model/IssueDomainAdminSSOTokenRequest';
import QuarantineNotificationsRequest from './model/QuarantineNotificationsRequest';
import QuarantineNotificationsRequestAttr from './model/QuarantineNotificationsRequestAttr';
import UpdateAliasRequest from './model/UpdateAliasRequest';
import UpdateAliasRequestAttr from './model/UpdateAliasRequestAttr';
import UpdateDomainRequest from './model/UpdateDomainRequest';
import UpdateDomainRequestAttr from './model/UpdateDomainRequestAttr';
import UpdateDomainWideFooterRequest from './model/UpdateDomainWideFooterRequest';
import UpdateDomainWideFooterRequestAttr from './model/UpdateDomainWideFooterRequestAttr';
import UpdateMailboxACLRequest from './model/UpdateMailboxACLRequest';
import UpdateMailboxACLRequestAttr from './model/UpdateMailboxACLRequestAttr';
import UpdateMailboxCustomAttributesRequest from './model/UpdateMailboxCustomAttributesRequest';
import UpdateMailboxCustomAttributesRequestAttr from './model/UpdateMailboxCustomAttributesRequestAttr';
import UpdateMailboxRequest from './model/UpdateMailboxRequest';
import UpdateMailboxRequestAttr from './model/UpdateMailboxRequestAttr';
import UpdatePushoverSettingsRequest from './model/UpdatePushoverSettingsRequest';
import UpdatePushoverSettingsRequestAttr from './model/UpdatePushoverSettingsRequestAttr';
import UpdateSyncJobRequest from './model/UpdateSyncJobRequest';
import UpdateSyncJobRequestAttr from './model/UpdateSyncJobRequestAttr';
import AddressRewritingApi from './api/AddressRewritingApi';
import AliasesApi from './api/AliasesApi';
import AppPasswordsApi from './api/AppPasswordsApi';
import CrossOriginResourceSharingCORSApi from './api/CrossOriginResourceSharingCORSApi';
import DKIMApi from './api/DKIMApi';
import DomainAdminApi from './api/DomainAdminApi';
import DomainAntispamPoliciesApi from './api/DomainAntispamPoliciesApi';
import DomainsApi from './api/DomainsApi';
import Fail2BanApi from './api/Fail2BanApi';
import FordwardingHostsApi from './api/FordwardingHostsApi';
import IdentityProviderApi from './api/IdentityProviderApi';
import LogsApi from './api/LogsApi';
import MailboxesApi from './api/MailboxesApi';
import OAuthClientsApi from './api/OAuthClientsApi';
import OutgoingTLSPolicyMapOverridesApi from './api/OutgoingTLSPolicyMapOverridesApi';
import QuarantineApi from './api/QuarantineApi';
import QueueManagerApi from './api/QueueManagerApi';
import RatelimitsApi from './api/RatelimitsApi';
import ResourcesApi from './api/ResourcesApi';
import RoutingApi from './api/RoutingApi';
import SingleSignOnApi from './api/SingleSignOnApi';
import StatusApi from './api/StatusApi';
import SyncJobsApi from './api/SyncJobsApi';


/**
* mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration &gt; Access &gt; Edit administrator details &gt; API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MailcowSdkJs = require('index'); // See note below*.
* var xxxSvc = new MailcowSdkJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MailcowSdkJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MailcowSdkJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MailcowSdkJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddForwardHostRequest model constructor.
     * @property {module:model/AddForwardHostRequest}
     */
    AddForwardHostRequest,

    /**
     * The CreateAlias200Response model constructor.
     * @property {module:model/CreateAlias200Response}
     */
    CreateAlias200Response,

    /**
     * The CreateAliasRequest model constructor.
     * @property {module:model/CreateAliasRequest}
     */
    CreateAliasRequest,

    /**
     * The CreateAppPasswordRequest model constructor.
     * @property {module:model/CreateAppPasswordRequest}
     */
    CreateAppPasswordRequest,

    /**
     * The CreateBCCMapRequest model constructor.
     * @property {module:model/CreateBCCMapRequest}
     */
    CreateBCCMapRequest,

    /**
     * The CreateDomainAdminUserRequest model constructor.
     * @property {module:model/CreateDomainAdminUserRequest}
     */
    CreateDomainAdminUserRequest,

    /**
     * The CreateDomainPolicyRequest model constructor.
     * @property {module:model/CreateDomainPolicyRequest}
     */
    CreateDomainPolicyRequest,

    /**
     * The CreateDomainRequest model constructor.
     * @property {module:model/CreateDomainRequest}
     */
    CreateDomainRequest,

    /**
     * The CreateMailboxRequest model constructor.
     * @property {module:model/CreateMailboxRequest}
     */
    CreateMailboxRequest,

    /**
     * The CreateOAuthClientRequest model constructor.
     * @property {module:model/CreateOAuthClientRequest}
     */
    CreateOAuthClientRequest,

    /**
     * The CreateRecipientMapRequest model constructor.
     * @property {module:model/CreateRecipientMapRequest}
     */
    CreateRecipientMapRequest,

    /**
     * The CreateResourcesRequest model constructor.
     * @property {module:model/CreateResourcesRequest}
     */
    CreateResourcesRequest,

    /**
     * The CreateSenderDependentTransportsRequest model constructor.
     * @property {module:model/CreateSenderDependentTransportsRequest}
     */
    CreateSenderDependentTransportsRequest,

    /**
     * The CreateSyncJobRequest model constructor.
     * @property {module:model/CreateSyncJobRequest}
     */
    CreateSyncJobRequest,

    /**
     * The CreateTLSPolicyMapRequest model constructor.
     * @property {module:model/CreateTLSPolicyMapRequest}
     */
    CreateTLSPolicyMapRequest,

    /**
     * The CreateTimeLimitedAliasRequest model constructor.
     * @property {module:model/CreateTimeLimitedAliasRequest}
     */
    CreateTimeLimitedAliasRequest,

    /**
     * The CreateTransportMapsRequest model constructor.
     * @property {module:model/CreateTransportMapsRequest}
     */
    CreateTransportMapsRequest,

    /**
     * The DeleteAppPasswordRequest model constructor.
     * @property {module:model/DeleteAppPasswordRequest}
     */
    DeleteAppPasswordRequest,

    /**
     * The DeleteBCCMapRequest model constructor.
     * @property {module:model/DeleteBCCMapRequest}
     */
    DeleteBCCMapRequest,

    /**
     * The DeleteDomainAdminRequest model constructor.
     * @property {module:model/DeleteDomainAdminRequest}
     */
    DeleteDomainAdminRequest,

    /**
     * The DeleteDomainPolicyRequest model constructor.
     * @property {module:model/DeleteDomainPolicyRequest}
     */
    DeleteDomainPolicyRequest,

    /**
     * The DeleteDomainRequest model constructor.
     * @property {module:model/DeleteDomainRequest}
     */
    DeleteDomainRequest,

    /**
     * The DeleteDomainTagsRequest model constructor.
     * @property {module:model/DeleteDomainTagsRequest}
     */
    DeleteDomainTagsRequest,

    /**
     * The DeleteForwardHostRequest model constructor.
     * @property {module:model/DeleteForwardHostRequest}
     */
    DeleteForwardHostRequest,

    /**
     * The DeleteMailboxRequest model constructor.
     * @property {module:model/DeleteMailboxRequest}
     */
    DeleteMailboxRequest,

    /**
     * The DeleteMailboxTagsRequest model constructor.
     * @property {module:model/DeleteMailboxTagsRequest}
     */
    DeleteMailboxTagsRequest,

    /**
     * The DeleteMailsInQuarantineRequest model constructor.
     * @property {module:model/DeleteMailsInQuarantineRequest}
     */
    DeleteMailsInQuarantineRequest,

    /**
     * The DeleteOAuthClientRequest model constructor.
     * @property {module:model/DeleteOAuthClientRequest}
     */
    DeleteOAuthClientRequest,

    /**
     * The DeleteQueueRequest model constructor.
     * @property {module:model/DeleteQueueRequest}
     */
    DeleteQueueRequest,

    /**
     * The DeleteRecipientMapRequest model constructor.
     * @property {module:model/DeleteRecipientMapRequest}
     */
    DeleteRecipientMapRequest,

    /**
     * The DeleteResourcesRequest model constructor.
     * @property {module:model/DeleteResourcesRequest}
     */
    DeleteResourcesRequest,

    /**
     * The DeleteSenderDependentTransportsRequest model constructor.
     * @property {module:model/DeleteSenderDependentTransportsRequest}
     */
    DeleteSenderDependentTransportsRequest,

    /**
     * The DeleteSyncJobRequest model constructor.
     * @property {module:model/DeleteSyncJobRequest}
     */
    DeleteSyncJobRequest,

    /**
     * The DeleteTLSPolicyMapRequest model constructor.
     * @property {module:model/DeleteTLSPolicyMapRequest}
     */
    DeleteTLSPolicyMapRequest,

    /**
     * The DeleteTransportMapsRequest model constructor.
     * @property {module:model/DeleteTransportMapsRequest}
     */
    DeleteTransportMapsRequest,

    /**
     * The DuplicateDKIMKeyRequest model constructor.
     * @property {module:model/DuplicateDKIMKeyRequest}
     */
    DuplicateDKIMKeyRequest,

    /**
     * The EditCrossOriginResourceSharingCORSSettingsRequest model constructor.
     * @property {module:model/EditCrossOriginResourceSharingCORSSettingsRequest}
     */
    EditCrossOriginResourceSharingCORSSettingsRequest,

    /**
     * The EditCrossOriginResourceSharingCORSSettingsRequestAttr model constructor.
     * @property {module:model/EditCrossOriginResourceSharingCORSSettingsRequestAttr}
     */
    EditCrossOriginResourceSharingCORSSettingsRequestAttr,

    /**
     * The EditDomainAdminACLRequest model constructor.
     * @property {module:model/EditDomainAdminACLRequest}
     */
    EditDomainAdminACLRequest,

    /**
     * The EditDomainAdminACLRequestAttr model constructor.
     * @property {module:model/EditDomainAdminACLRequestAttr}
     */
    EditDomainAdminACLRequestAttr,

    /**
     * The EditDomainAdminUserRequest model constructor.
     * @property {module:model/EditDomainAdminUserRequest}
     */
    EditDomainAdminUserRequest,

    /**
     * The EditDomainAdminUserRequestAttr model constructor.
     * @property {module:model/EditDomainAdminUserRequestAttr}
     */
    EditDomainAdminUserRequestAttr,

    /**
     * The EditDomainRatelimitsRequest model constructor.
     * @property {module:model/EditDomainRatelimitsRequest}
     */
    EditDomainRatelimitsRequest,

    /**
     * The EditExternalIdentityProviderSettingsRequest model constructor.
     * @property {module:model/EditExternalIdentityProviderSettingsRequest}
     */
    EditExternalIdentityProviderSettingsRequest,

    /**
     * The EditExternalIdentityProviderSettingsRequestAttr model constructor.
     * @property {module:model/EditExternalIdentityProviderSettingsRequestAttr}
     */
    EditExternalIdentityProviderSettingsRequestAttr,

    /**
     * The EditFail2BanRequest model constructor.
     * @property {module:model/EditFail2BanRequest}
     */
    EditFail2BanRequest,

    /**
     * The EditFail2BanRequestAttr model constructor.
     * @property {module:model/EditFail2BanRequestAttr}
     */
    EditFail2BanRequestAttr,

    /**
     * The EditMailboxRatelimitsRequest model constructor.
     * @property {module:model/EditMailboxRatelimitsRequest}
     */
    EditMailboxRatelimitsRequest,

    /**
     * The EditMailboxRatelimitsRequestAttr model constructor.
     * @property {module:model/EditMailboxRatelimitsRequestAttr}
     */
    EditMailboxRatelimitsRequestAttr,

    /**
     * The FlushQueueRequest model constructor.
     * @property {module:model/FlushQueueRequest}
     */
    FlushQueueRequest,

    /**
     * The GenerateDKIMKeyRequest model constructor.
     * @property {module:model/GenerateDKIMKeyRequest}
     */
    GenerateDKIMKeyRequest,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The IssueDomainAdminSSOTokenRequest model constructor.
     * @property {module:model/IssueDomainAdminSSOTokenRequest}
     */
    IssueDomainAdminSSOTokenRequest,

    /**
     * The QuarantineNotificationsRequest model constructor.
     * @property {module:model/QuarantineNotificationsRequest}
     */
    QuarantineNotificationsRequest,

    /**
     * The QuarantineNotificationsRequestAttr model constructor.
     * @property {module:model/QuarantineNotificationsRequestAttr}
     */
    QuarantineNotificationsRequestAttr,

    /**
     * The UpdateAliasRequest model constructor.
     * @property {module:model/UpdateAliasRequest}
     */
    UpdateAliasRequest,

    /**
     * The UpdateAliasRequestAttr model constructor.
     * @property {module:model/UpdateAliasRequestAttr}
     */
    UpdateAliasRequestAttr,

    /**
     * The UpdateDomainRequest model constructor.
     * @property {module:model/UpdateDomainRequest}
     */
    UpdateDomainRequest,

    /**
     * The UpdateDomainRequestAttr model constructor.
     * @property {module:model/UpdateDomainRequestAttr}
     */
    UpdateDomainRequestAttr,

    /**
     * The UpdateDomainWideFooterRequest model constructor.
     * @property {module:model/UpdateDomainWideFooterRequest}
     */
    UpdateDomainWideFooterRequest,

    /**
     * The UpdateDomainWideFooterRequestAttr model constructor.
     * @property {module:model/UpdateDomainWideFooterRequestAttr}
     */
    UpdateDomainWideFooterRequestAttr,

    /**
     * The UpdateMailboxACLRequest model constructor.
     * @property {module:model/UpdateMailboxACLRequest}
     */
    UpdateMailboxACLRequest,

    /**
     * The UpdateMailboxACLRequestAttr model constructor.
     * @property {module:model/UpdateMailboxACLRequestAttr}
     */
    UpdateMailboxACLRequestAttr,

    /**
     * The UpdateMailboxCustomAttributesRequest model constructor.
     * @property {module:model/UpdateMailboxCustomAttributesRequest}
     */
    UpdateMailboxCustomAttributesRequest,

    /**
     * The UpdateMailboxCustomAttributesRequestAttr model constructor.
     * @property {module:model/UpdateMailboxCustomAttributesRequestAttr}
     */
    UpdateMailboxCustomAttributesRequestAttr,

    /**
     * The UpdateMailboxRequest model constructor.
     * @property {module:model/UpdateMailboxRequest}
     */
    UpdateMailboxRequest,

    /**
     * The UpdateMailboxRequestAttr model constructor.
     * @property {module:model/UpdateMailboxRequestAttr}
     */
    UpdateMailboxRequestAttr,

    /**
     * The UpdatePushoverSettingsRequest model constructor.
     * @property {module:model/UpdatePushoverSettingsRequest}
     */
    UpdatePushoverSettingsRequest,

    /**
     * The UpdatePushoverSettingsRequestAttr model constructor.
     * @property {module:model/UpdatePushoverSettingsRequestAttr}
     */
    UpdatePushoverSettingsRequestAttr,

    /**
     * The UpdateSyncJobRequest model constructor.
     * @property {module:model/UpdateSyncJobRequest}
     */
    UpdateSyncJobRequest,

    /**
     * The UpdateSyncJobRequestAttr model constructor.
     * @property {module:model/UpdateSyncJobRequestAttr}
     */
    UpdateSyncJobRequestAttr,

    /**
    * The AddressRewritingApi service constructor.
    * @property {module:api/AddressRewritingApi}
    */
    AddressRewritingApi,

    /**
    * The AliasesApi service constructor.
    * @property {module:api/AliasesApi}
    */
    AliasesApi,

    /**
    * The AppPasswordsApi service constructor.
    * @property {module:api/AppPasswordsApi}
    */
    AppPasswordsApi,

    /**
    * The CrossOriginResourceSharingCORSApi service constructor.
    * @property {module:api/CrossOriginResourceSharingCORSApi}
    */
    CrossOriginResourceSharingCORSApi,

    /**
    * The DKIMApi service constructor.
    * @property {module:api/DKIMApi}
    */
    DKIMApi,

    /**
    * The DomainAdminApi service constructor.
    * @property {module:api/DomainAdminApi}
    */
    DomainAdminApi,

    /**
    * The DomainAntispamPoliciesApi service constructor.
    * @property {module:api/DomainAntispamPoliciesApi}
    */
    DomainAntispamPoliciesApi,

    /**
    * The DomainsApi service constructor.
    * @property {module:api/DomainsApi}
    */
    DomainsApi,

    /**
    * The Fail2BanApi service constructor.
    * @property {module:api/Fail2BanApi}
    */
    Fail2BanApi,

    /**
    * The FordwardingHostsApi service constructor.
    * @property {module:api/FordwardingHostsApi}
    */
    FordwardingHostsApi,

    /**
    * The IdentityProviderApi service constructor.
    * @property {module:api/IdentityProviderApi}
    */
    IdentityProviderApi,

    /**
    * The LogsApi service constructor.
    * @property {module:api/LogsApi}
    */
    LogsApi,

    /**
    * The MailboxesApi service constructor.
    * @property {module:api/MailboxesApi}
    */
    MailboxesApi,

    /**
    * The OAuthClientsApi service constructor.
    * @property {module:api/OAuthClientsApi}
    */
    OAuthClientsApi,

    /**
    * The OutgoingTLSPolicyMapOverridesApi service constructor.
    * @property {module:api/OutgoingTLSPolicyMapOverridesApi}
    */
    OutgoingTLSPolicyMapOverridesApi,

    /**
    * The QuarantineApi service constructor.
    * @property {module:api/QuarantineApi}
    */
    QuarantineApi,

    /**
    * The QueueManagerApi service constructor.
    * @property {module:api/QueueManagerApi}
    */
    QueueManagerApi,

    /**
    * The RatelimitsApi service constructor.
    * @property {module:api/RatelimitsApi}
    */
    RatelimitsApi,

    /**
    * The ResourcesApi service constructor.
    * @property {module:api/ResourcesApi}
    */
    ResourcesApi,

    /**
    * The RoutingApi service constructor.
    * @property {module:api/RoutingApi}
    */
    RoutingApi,

    /**
    * The SingleSignOnApi service constructor.
    * @property {module:api/SingleSignOnApi}
    */
    SingleSignOnApi,

    /**
    * The StatusApi service constructor.
    * @property {module:api/StatusApi}
    */
    StatusApi,

    /**
    * The SyncJobsApi service constructor.
    * @property {module:api/SyncJobsApi}
    */
    SyncJobsApi
};
