/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailcowSdkJs);
  }
}(this, function(expect, MailcowSdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailcowSdkJs.MailboxesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MailboxesApi', function() {
    describe('createMailbox', function() {
      it('should call createMailbox successfully', function(done) {
        //uncomment below and update the code to test createMailbox
        //instance.createMailbox(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMailbox', function() {
      it('should call deleteMailbox successfully', function(done) {
        //uncomment below and update the code to test deleteMailbox
        //instance.deleteMailbox(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMailboxTags', function() {
      it('should call deleteMailboxTags successfully', function(done) {
        //uncomment below and update the code to test deleteMailboxTags
        //instance.deleteMailboxTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editMailboxSpamFilterScore', function() {
      it('should call editMailboxSpamFilterScore successfully', function(done) {
        //uncomment below and update the code to test editMailboxSpamFilterScore
        //instance.editMailboxSpamFilterScore(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMailboxOrGlobalSpamFilterScore', function() {
      it('should call getMailboxOrGlobalSpamFilterScore successfully', function(done) {
        //uncomment below and update the code to test getMailboxOrGlobalSpamFilterScore
        //instance.getMailboxOrGlobalSpamFilterScore(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMailboxes', function() {
      it('should call getMailboxes successfully', function(done) {
        //uncomment below and update the code to test getMailboxes
        //instance.getMailboxes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMailboxesOfADomain', function() {
      it('should call getMailboxesOfADomain successfully', function(done) {
        //uncomment below and update the code to test getMailboxesOfADomain
        //instance.getMailboxesOfADomain(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quarantineNotifications', function() {
      it('should call quarantineNotifications successfully', function(done) {
        //uncomment below and update the code to test quarantineNotifications
        //instance.quarantineNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMailbox', function() {
      it('should call updateMailbox successfully', function(done) {
        //uncomment below and update the code to test updateMailbox
        //instance.updateMailbox(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMailboxACL', function() {
      it('should call updateMailboxACL successfully', function(done) {
        //uncomment below and update the code to test updateMailboxACL
        //instance.updateMailboxACL(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMailboxCustomAttributes', function() {
      it('should call updateMailboxCustomAttributes successfully', function(done) {
        //uncomment below and update the code to test updateMailboxCustomAttributes
        //instance.updateMailboxCustomAttributes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePushoverSettings', function() {
      it('should call updatePushoverSettings successfully', function(done) {
        //uncomment below and update the code to test updatePushoverSettings
        //instance.updatePushoverSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
