/**
 * mailcow API
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailcowSdkJs);
  }
}(this, function(expect, MailcowSdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailcowSdkJs.RoutingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RoutingApi', function() {
    describe('createSenderDependentTransports', function() {
      it('should call createSenderDependentTransports successfully', function(done) {
        //uncomment below and update the code to test createSenderDependentTransports
        //instance.createSenderDependentTransports(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createTransportMaps', function() {
      it('should call createTransportMaps successfully', function(done) {
        //uncomment below and update the code to test createTransportMaps
        //instance.createTransportMaps(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSenderDependentTransports', function() {
      it('should call deleteSenderDependentTransports successfully', function(done) {
        //uncomment below and update the code to test deleteSenderDependentTransports
        //instance.deleteSenderDependentTransports(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTransportMaps', function() {
      it('should call deleteTransportMaps successfully', function(done) {
        //uncomment below and update the code to test deleteTransportMaps
        //instance.deleteTransportMaps(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSenderDependentTransports', function() {
      it('should call getSenderDependentTransports successfully', function(done) {
        //uncomment below and update the code to test getSenderDependentTransports
        //instance.getSenderDependentTransports(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTransportMaps', function() {
      it('should call getTransportMaps successfully', function(done) {
        //uncomment below and update the code to test getTransportMaps
        //instance.getTransportMaps(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
